### ISSUE TITLE
Remove requirements.txt and update setup.py

### ISSUE THREAD

**Issue by Gustry** [kartoza/geonode#107]
Remove requirements.txt and update setup.py
BTW, do we need south ? I read it's not needed with the new django version ?
Also, we need to clean local_settings_example.py, there are some duplication about qgis_server

**Comment by timlinux** [comment]
Yeah south is not needed anymore since we have django migrations.
Requirements can go .

**Comment by timlinux** [comment]
By the way thinking about this some more, we should try to make the smallest delta possible between their code tree and ours, so unless there is a need to remove stuff, lets just leave it there.

**Comment by gubuntu** [comment]
I'm sure this is sorted
