### ISSUE TITLE
Geonode Internal Server Error. but why???

### ISSUE THREAD

**Issue by Javiermx** [kartoza/geonode#111]
System
Geonode 2.4
Ubuntu 14.04.4 LTS (GNU/Linux 3.16.0-30-generic x86_64)

Problem:
Internal Server Error (500)
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator at webmaster@localhost to inform them of the time this error occurred, and the actions you performed just before this error.
More information about this error may be available in the server error log.
________________________________________
Apache/2.4.7 (Ubuntu) Server at 192.168.1.94 Port 80
------------------------------------------------------------------------------
When I'm disconnected from the system.
http://192.168.1.94/ don’t work
http://192.168.1.94/layers/ don’t work

http://192.168.1.94/admin/ YES work
http://192.168.1.94/account/login/ YES work
http://192.168.1.94/geoserver/web/ YES work
------------------------------------------------------------------------------

if I enter the system (loged):
loged, http://192.168.1.94/  if it works well
loged, http://192.168.1.94/layers/ if it works well

But if I try to upload a new layer (loged): Profile matching query does not exist.

When I try to logout: Internal Server Error (500)

[apache (log).txt](https://github.com/kartoza/geonode/files/337912/apache.log.txt)
[geonode (log).txt](https://github.com/kartoza/geonode/files/337911/geonode.log.txt)

**Comment by Gustry** [comment]
You should ask your question on the main Geonode repository : https://github.com/GeoNode/geonode

But it seems you didn't install geonode correctly. You should check your logs /var/logs to see what happened behind the error 500.

**Comment by Javiermx** [comment]
8 months ago GeoNode install, and it was working fine.


________________________________
De: Etienne Trimaille <notifications@github.com>
Enviado: martes, 28 de junio de 2016 07:48 p. m.
Para: kartoza/geonode
Cc: Javiermx; Author
Asunto: Re: [kartoza/geonode] Geonode Internal Server Error. but why??? (#111)


You should ask your question on the main Geonode repository : https://github.com/GeoNode/geonode

[https://avatars0.githubusercontent.com/u/132843?v=3&s=400]<https://github.com/GeoNode/geonode>

GitHub - GeoNode/geonode: GeoNode is an open source ...<https://github.com/GeoNode/geonode>
github.com
geonode - GeoNode is an open source platform that facilitates the creation, sharing, and collaborative use of geospatial data.



But it seems you didn't install geonode correctly. You should check your logs /var/logs to see what happened behind the error 500.

-

**Comment by Javiermx** [comment]
because reason you deleted, not just you moved


________________________________
De: Etienne Trimaille <notifications@github.com>
Enviado: martes, 28 de junio de 2016 07:48 p. m.
Para: kartoza/geonode
Cc: Javiermx; Author
Asunto: Re: [kartoza/geonode] Geonode Internal Server Error. but why??? (#111)


Closed #111<https://github.com/kartoza/geonode/issues/111>.

-
