### ISSUE TITLE
Rendering problem on branch qgis_server_backend

### ISSUE THREAD

**Issue by ldgeo** [kartoza/geonode#121]
Hello,

i've tried several ways to have qgis-server backend working (branches develop, master, qgis_server and qgis_server_backend). Only  `qgis_backend_server` seems to work with a quick fix related to the configuration (https://github.com/ldgeo/geonode/commit/d552c2ba45fc4b82c31519267b7590252cff5072)  

i've managed to load some layers, i'm able to view layers with tiles generated from qgis-server but 
it seems that tiles are sometimes shifted (any problem on bbox, accuracy?)

Any ideas for this problem or any fix in newer commits ? 

![layers_problem](https://cloud.githubusercontent.com/assets/1412193/18132368/d5723580-6f96-11e6-9920-2f4c1355b270.png)

additionnal infos: 
* Ubuntu 1604
* qgis-server package from http://qgis.org/debian
* geonode_qgis_server installed with pip

**Comment by Gustry** [comment]
Hello,

This was an old bug, that we have fixed. See #74.  Is is possible to give your CRS for this layer ? I'm going to try again on my side.

**Comment by leny-pa** [comment]
Hi,

CRS of the screenshot layer is WGS84 4326.
I did a test with a reprojected layer in 3857. It is worst, the layer is not visible at all.

**Comment by Gustry** [comment]
4326 or 3857 or whatever projection should work.

I will have a look on a new geonode instance soon.

**Comment by ldgeo** [comment]
Ok your fix is in develop branch, but i used  geonode-qgis-server from @ismailsunni 

https://github.com/ismailsunni/geonode_qgis_server/blob/develop/geonode_qgis_server/views.py
doesn't have the fix.

I applied the diff to views.py and it seems to fix the problem. 

Could you shed some lights on the status of  the qgis server backend ?   
What branch we should use at this time ?
The PR from Ismail has been merged into geonode but lack of some fixes (like the solution of this issue)

**Comment by ldgeo** [comment]
ok fixed in kartoza/geonode_qgis_server/pull/6
