### ISSUE TITLE
Long running process stalls on geonode.kartoza.com

### ISSUE THREAD

**Issue by timlinux** [kartoza/geonode#122]
Hi @lucernae 

@vdeparday has reported that trying to do a full analysis is timing out. I can see in the analysis list there are a bunch of pending jobs. Can you check if celery is running or what is going on? See screenshot below. Please treat this as urgent as @vdeparday is trying to demo it to people and we need it to be bullet proof....

![screen shot 2016-09-21 at 7 51 46 pm](https://cloud.githubusercontent.com/assets/178003/18722406/058320be-8035-11e6-8b27-4975b5cbe6fd.png)

**Comment by lucernae** [comment]
It takes too long for polygon flood on roads to complete, so it blocks other tasks.
I will try to find a workaround.

**Comment by lucernae** [comment]
Solve this by:
- Running 4 celery workers to process as many concurrent process as possible
- Disable tasks prefetching using Celery config:

   ```
CELERY_ACKS_LATE = True
CELERYD_PREFETCH_MULTIPLIER = 1
   ```

- Disable tasks prefetching using celery worker optimization flag (-Ofair):

   ```
xvfb-run -a --server-args="-screen 0, 1024x768x24" celery -A headless.celery_app worker -Q inasafe-headless -l info -Ofair
   ```

- Will document this for Hendrik.

**Comment by timlinux** [comment]
Hi @lucernae 

I tested it with roads on RW poles and it seemed to generate the result, but I had to reload the analysis view and then manually select the impact layer in order to see the result. Can you check on that?

**Comment by timlinux** [comment]
And thanks for the fixes so far by the way!

**Comment by gubuntu** [comment]
This issue was moved to kartoza/geosafe#268
