### ISSUE TITLE
Provide hints to user when loading the analysis page

### ISSUE THREAD

**Issue by timlinux** [kartoza/geonode#123]
@vdeparday asked that we add a few dialogs
- [ ] when you open the page 'Select an exposure' (with a call out pointing the exposure section), 
- [ ] 'Select a hazard' which should show after exposure is selected.
- [ ] 'Press run when you are ready which should appear after the hazard is selected.

I think this makes sense to me and will make things much clearer for the user.

**Comment by gubuntu** [comment]
This issue was moved to kartoza/geosafe#269
