### ISSUE TITLE
Missing thumbnail on upload

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geonode#125]
# Problem
When you upload a hazard/exposure layer the layer preview is empty.

![prev](https://cloud.githubusercontent.com/assets/2510900/21096306/1376f362-c068-11e6-87d0-a8ad2b349cc4.png)

related #195 and #233

#Solution

Fix and show layer preview

**Comment by gubuntu** [comment]
please test again @NyakudyaA

**Comment by NyakudyaA** [comment]
Uploaded various layer and it is working properly
