### ISSUE TITLE
Misaligned tiles on upload of layer to geonode

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geonode#128]
# Problem

When uploading layers to geonode the layers geometry/shape is incorrect. The geometry is incorrectly rendered.

![screen-shot-2016-12-09-at-2 26 48-pm](https://cloud.githubusercontent.com/assets/2510900/21049560/3eab7e5a-be1e-11e6-98de-bb05141f1b95.png)

# Solution

Render the layers correctly

**Comment by gubuntu** [comment]
@NyakudyaA is this just a metatiling issue or something else? or is it still even an issue?

**Comment by NyakudyaA** [comment]
@gubuntu  I think it is a metatiling issue but cannot reproduce this behavior.
