### ISSUE TITLE
Upload error when running concurent processes. A process in geosafe and upload of layer

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geonode#129]
# Problem

When trying to upload a layer in geonode whilst running analysis using a big layer causes an upload error.

![upload](https://cloud.githubusercontent.com/assets/2510900/21042882/ece1aab6-bdfc-11e6-91bb-55182a7d88a9.png)

# Solution

Fix upload.

N.B - There is a current analysis running in another geosafe tab. 
* Hazard Layer - geonode:nsunga_tanzania
* Impact Layer - geonode:osm_buildings_current_tanzania

**Comment by gubuntu** [comment]
This issue was moved to kartoza/geosafe#272
