### ISSUE TITLE
Analysis list url is broken when opening another geosafe and remove debug mode in production

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geonode#131]
# Problem

I have  analysis running another tab and when I open another instance of geosafe in a different tab. I cannot get the analysis list.
![analysis](https://cloud.githubusercontent.com/assets/2510900/21041359/2c0eab6c-bdf3-11e6-92d2-5a34cac06d8e.png)

# Solution

Fix and let the user see the analysis list. 
Give nice error codes. Do not run geonode in debug mode on production.

**Comment by gubuntu** [comment]
This issue was moved to kartoza/geosafe#274
