### ISSUE TITLE
Layers are not properly uploaded to geonode

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geonode#136]
# Problem

Uploading a land cover layer results in no layer preview for that layer. 
The following is the layer in QGIS:

![landcover](https://cloud.githubusercontent.com/assets/2510900/21420412/49516a5a-c836-11e6-9c24-3812203cbbf9.png)

After upload of the layer in geonode:
![landcover_geo](https://cloud.githubusercontent.com/assets/2510900/21420449/7c3d772e-c836-11e6-9a61-ed5b465fa5d2.png)

Dataset: `inasafe/safe/test/data/exposure/landcover.shp`

# Solution 

Fix

**Comment by gubuntu** [comment]
what CRS was the layer? if not 4326 then it's because of #275

**Comment by NyakudyaA** [comment]
Uploads now work properly for this layer.
![ayer](https://user-images.githubusercontent.com/2510900/45107665-a3da1c80-b13a-11e8-89d2-344e67895980.png)
