### ISSUE TITLE
show analysis results in empty tables and reports after running analysis

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geonode#138]
# Problem

After running an analysis I click on show analysis summary:

Earthquakes on buildings

Data:
* Exposure: `inasafe/safe/test/data/exposure/buildings.shp`
* Hazard: `inasafe/safe/test/data/hazard/classified_generic_polygon.shp`

![analysis_resu](https://cloud.githubusercontent.com/assets/2510900/21423621/bd11bf84-c846-11e6-821c-7bfe2dd837bb.png)

Then clicking on show map report and show table report all result in black outputs:

![impact_report](https://cloud.githubusercontent.com/assets/2510900/21423655/e4c38274-c846-11e6-8b58-816363abaf70.png)
![report](https://cloud.githubusercontent.com/assets/2510900/21423656/e4c6d1fe-c846-11e6-91c6-50ea99fabfe2.png)

# Solution

All results should be visible

**Comment by gubuntu** [comment]
This issue was moved to kartoza/geosafe#278
