### ISSUE TITLE
Report map does not show complete words after running analysis in geosafe

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geonode#140]
# Problem 
After running analysis the reports that are generated do not show complete words for all items highlighted.

![version](https://cloud.githubusercontent.com/assets/2510900/21452200/fa8d92ee-c90d-11e6-9b06-79f40c11c2ce.png)

# Solution

Fix to show Inasafe version

**Comment by gubuntu** [comment]
This issue was moved to kartoza/geosafe#279
