### ISSUE TITLE
Fully populated metadata with all the proper tags

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geonode#141]
# Problem

After starting geonode it seems not all fields are populated properly. 

This helps in Populating metadata properly.

![cat](https://cloud.githubusercontent.com/assets/2510900/22197849/825a8400-e15c-11e6-9a2e-212c6403fb1d.png)
![regions](https://cloud.githubusercontent.com/assets/2510900/22197850/825b69d8-e15c-11e6-90fb-14a2ce137c78.png)

# Solution
We need to run `python manage.py loaddata geonode/base/fixtures/initial_data.json` 

![tt](https://cloud.githubusercontent.com/assets/2510900/22197882/9f3789ec-e15c-11e6-9c47-c81f6daeff11.png)
![cat1](https://cloud.githubusercontent.com/assets/2510900/22197883/9f3aebaa-e15c-11e6-8716-aa1280336a63.png)

**Comment by ismailsunni** [comment]
Is it more for geonode not geosafe?

**Comment by gubuntu** [comment]
@lucernae add this to docker config?

**Comment by lucernae** [comment]
Does this issue still relevant?

> @lucernae add this to docker config?

Also not sure what you meant by docker config?

**Comment by gubuntu** [comment]
yes I think this should be a standard part of our GeoNode install, i.e. that manage.py command should be run during orchestration / image building. 

Low priority, so don't do it now...just put down your thoughts

**Comment by NyakudyaA** [comment]
@gubuntu This is no longer an issue. In earlier versions geonode the docker, the orchestration was not executing `python manage.py loaddata geonode/base/fixtures/initial_data.json` but now I think all setup is executing that. I will close this now. 
![regions](https://user-images.githubusercontent.com/2510900/30732351-777b6408-9f72-11e7-991b-76c8c3855b2d.png)
