### ISSUE TITLE
Metadata preserve does not allow correct metadata download

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geonode#142]
# Problem

Using the preserve metadata when uploading layers result in the generated metadata not being editable. Also when downloading a layer's metadata that was uploaded with the preserve metadata tag it results in metadata without keywords being generated.

![safe](https://cloud.githubusercontent.com/assets/2510900/22198836/f7d2e6ce-e160-11e6-8de7-a5bdb693a944.png)

# Solution

Allow metadata to be downloaded with all insafe keywords regardless of how the layer was uploaded.
Add an option that  allows the raw metadata to be downloaded

**Comment by gubuntu** [comment]
@NyakudyaA pls test again and comment or close. Not a duplicate of #211?

**Comment by NyakudyaA** [comment]
Metadata can be downloaded now even when using the preserve metadata.
