### ISSUE TITLE
Separate out GeoServer and QGIS Server implementation details from geonode/maps into the backend specific maps rather

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geonode#146]
GeoServer and QGIS Server map composition is handled with two different code bases due to the differences in how the backends work. For example in https://github.com/GeoNode/geonode/tree/master/geonode/maps we have both QGIS code and GeoServer code - these implementation details should be backend specific rather (related to #145 R&D?) and be moved into their respective backend apps (related to #144?). (i.e. this Issue is not about actually doing these two items. correct @timlinux ?) 

Currently the QGIS GeoNode backend is implemented as its own contrib application. __For this work item we will incorporate the QGIS GeoNode directly into the core GeoNode code base so that it is always available when GeoNode is installed.__ The administrator will still need to ensure that the QGIS Server backend and QGIS Server Plugin are available on the server.

**Comment by lucernae** [comment]
All maps related code is in geonode.maps package. So, my proposed approach would be to review all the urlpattern for that package. @ismailsunni and @Gustry had already made switching code in the past, however, we don't have any reiliable way of testing which works at the moment.

Here's the list of urlpattern as of now:

- [ ] map browse
- [ ] new map
- [ ] new map json
- [ ] ajax url lookup
- [ ] create map snapshot
- [ ] map detail
- [ ] map view
- [ ] map edit
- [ ] map json
- [ ] map download
- [ ] map wmc
- [ ] map wms
- [ ] map remove
- [ ] map metadata
- [ ] map embed
- [ ] map history (history of snapshots)
- [ ] map thumbnail
- [ ] map view by snapshot
- [ ] map detail by snapshot
- [ ] map embed by snapshot
- [ ] map json by snapshot
- [ ] map download check
- [ ] map embed
- [ ] map metadata detail
- [ ] map layer attributes

Some of the urls were already implemented. We need to refactor (make it tidy) and make the tests switch for corresponding backend.

**Comment by gubuntu** [comment]
@lucernae see my updates to OP, in light of which I think your comment should be moved to #144 or #145 and in this Issue focus on the sentence in __bold__.

**Comment by ismailsunni** [comment]
Checking the bold sentence, I think this has been done by @lucernae in the current pull request. Or is there anything else that we need to do?

**Comment by gubuntu** [comment]
yes I propose we close this. You want to weigh in @timlinux?

**Comment by lucernae** [comment]
We can close this, Pull request for unittest were merged
