### ISSUE TITLE
Add styling / style support

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geonode#149]
Prior to this contract extension we had implemented support for uploading QGIS ‘qml’ style files when registering a layer with GeoNode. In this contract extension we propose to build on this prior work by providing a richer set of ways in which QGIS style files can be associated with a GeoNode layer. Specifically:
- The ability to replace the style file for a layer with a new / updated one
- The ability to associate more than one style file for a layer (and then let the user select which one they would like to use)
- The ability to download style files to improve them offline in QGIS (and then subsequently upload them to GeoNode again)

This functionality must be available through the GeoNode API and implemented for this Issue in the GeoNode UI (implementation in QGIS is covered by https://github.com/kartoza/QGIS/issues/18)

**Comment by gubuntu** [comment]
Since GeoNode 2.6, which can now apply a qml style to a geoserver backend layer by converting it to SLD,  we should perhaps use the UI and parts of the same API to apply qml styles to QGIS backend layers

**Comment by ismailsunni** [comment]
API needed for style:
- [ ] List all available styles
- [ ] List style for a layer (should be in the layer API)
- [ ] Download specific style
- [ ] Upload new style file (.qml)
- [ ] Replace style

**Comment by gubuntu** [comment]
Please try to complete this week

**Comment by lucernae** [comment]
@ismailsunni what do you mean by list available styles? Does QGIS Server backend must support multiple styles and style management?

**Comment by ismailsunni** [comment]
CMIIW, in geoserver we have that multiple styles and style management. So, may be we can do the same. Although, I know that in the current implementation it's not easy to do. We need to generate one project file for each 
But for my current use case, as long as I can download, upload, and replace, it should be enough.

**Comment by lucernae** [comment]
@gubuntu 

IMO,  supporting multiple styles and style management for QGIS Server is a big task, I can't possibly finish that this week. The style model of current geonode tightly integrated with geoserver and only support sld. We had to create another model for QGIS Server to save multiple styles and management. QGIS Server also doesn't natively manage styles. So we had to create our own UI for managing styles for QGIS Server.

What's possible for now is to provide @ismailsunni (based on our discussion) with a style API for geonode to query these styles and hide details about the backend we used. This functionality then will be used by him for QGIS client features.

From users perspective, we can download QGIS Server style and Upload/replace style now through Geonode UI. But no support for layer management yet.

**Comment by gubuntu** [comment]
QGIS (and QGIS WMS server) supports multiple named styles for a layer. And a named style can be specified in a WMS request. 

If there is only one style it is used as the default style. 

A WMS GetCapabilities returns all named styles. 

So listing and usage of alternative styles can all be done via WMS.

Updating and adding extra named styles to a layer should be possible via the QGIS API. 

So @lucernae I'm not sure the obstacles are so big.

**Comment by Gustry** [comment]
As @gubuntu said, no need to generate one project per style. It's already in QGIS Server: many styles for one layer.

**Comment by lucernae** [comment]
The obstacles is:

- Create UI for managing multiple styles in Geonode (upload, delete, set default).
- The style management in Geonode is for the whole Geonode (can be shared accross layers), not for one project/layer. We could limit the requirement to only for multiple styles for one project.
- The styles is saved inside QGIS Project (.qgs), do we already have an API (maybe WMS or QGIS web request) to request specific style from inside .qgs, then download it as QML file? If there is, it sure a big help. @Gustry can you point this out if it is already exists?
- Do we already have WMS GetCapabilities implemented?

**Comment by gubuntu** [comment]
@lucernae obstacles are for overcoming!

- I think we limit ourselves to styles per layer. Many styles you can not share. If they use attributes e.g. rule-based or classified they will only work with one type of data. So if you do want to share you can download QML from one layer and upload to another. 
- QGIS implements WMS GetCapabilities, the question is whether GeoNode/Django handles it via its proxy API?

**Comment by lucernae** [comment]
> @lucernae obstacles are for overcoming!

Hahaha, yes of course. I list the obstacles to give the idea about the size of the task 😄 .
