### ISSUE TITLE
Download Leaflet page

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geonode#151]
Download ready to use leaflet page which references a layer via tile service. The implementation here would make it trivial to add a map hosted by GeoNode in a different web site. JavaScript references will be done using CDN (Content Distribution Network) references so that there are no local hosting requirements and the html can be directly inserted into a content management system. Implemented for QGIS Backend only.

**Comment by lucernae** [comment]
From what I read, it seems you want to download some kind of leaflet html code with layers embedded?

Is this specification ok?

- The html code will only provides standard leaflet plugins (not like what we see in Geonode's layer details, where there are many 3rd party plugins.)
- Does this in the format of iframe, or just plain static html?

**Comment by gubuntu** [comment]
It could be a div element or a full iframe - a snippet that someone can paste into their page to see a live map of that layer. Like typical 'download and embeddable widget' functionality found on many websites.

**Comment by gubuntu** [comment]
@boney-bun have you started on this? Should be a simple variation of the iframe and embed widget downloads

**Comment by gubuntu** [comment]
passed test

although it is incomplete (#365), let's get this delivered
