### ISSUE TITLE
Create downloadable QGIS project on the fly

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geonode#157]
Create downloadable QGIS project on the fly that references GeoNode layers including setting the mime type to pop up in QGIS after downloading. This is similar to the .qlr file download for maps, but instead of providing the user with a QGIS .qlr, we will instead generate a QGIS project file (.qgs) which they can open locally on their computer. QGIS Backend only.

Zip the file for download

Will use https://github.com/kartoza/otf-project

**Comment by Gustry** [comment]
@gubuntu What is the priority of this?

I guess it shouldn't be too complex, as we may only update paths using the existing QGIS project. Only a string replacement in the XML in the Django view. Let's check.

**Comment by Gustry** [comment]
Done in OTF-plugin to generate QLR and QGS usign remote layers.

I wouldn't zip it. It's only a small XML file, the size will not change a lot (users doesn't care about a few kb more when they use geonode I guess), and it's easier for the user to not unzip it.

**Comment by timlinux** [comment]
The File extension must be .qgs not .qgs.xml. or the file won't open in QGIS
The download link text should be "QGIS Project file" not "QGS Layer file"
The layer name in the project file should match the layer name in GeoNode i.e. Nepal Earthquake on buildings, not "tmpn9rmqv"

**Comment by gubuntu** [comment]
passed on testing, except for #360. But let's deliver what we have.
