### ISSUE TITLE
download original raster

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geonode#159]
Full Issue is #156 in Sprint2 but I'm bringing this part forward so users of http://geonode.inasafe.org can download usable rasters. 

# Proposed Solution

make a url to the original raster layer (.tiff or .asc)

Then test and deploy on the InaSAFE Geonode instance.

**Comment by gubuntu** [comment]
asc done in #181
tiff still needs doing (?)

needed for ThinkHazard

**Comment by gubuntu** [comment]
An example of a layer showing only 'Tile' download option: http://staging.geonode.kartoza.com/layers/geonode:npl_ppp_v2c_2011

It should be showing asc or GeoTiff as well.

**Comment by ismailsunni** [comment]
Fixed in #232
