### ISSUE TITLE
Disable Geoserver link in the user menu

### ISSUE THREAD

**Issue by Gustry** [kartoza/geonode#165]
If we use the QGIS Server backend, we shouldn't have the geoserver link
![screen shot 2017-04-12 at 10 06 47](https://cloud.githubusercontent.com/assets/1609292/24947621/ccffbf72-1f67-11e7-9255-0f9ca77aa6cb.png)

**Comment by boney-bun** [comment]
I have commented the link to GeoServer, so it disabled now.

![screen shot 2017-04-14 at 12 42 43 pm](https://cloud.githubusercontent.com/assets/4602383/25029382/e0f5f406-2110-11e7-8cf8-f5118408c31b.png)
