### ISSUE TITLE
Upload error on big rasters

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geonode#193]
# Problem

When trying to upload raster layers that are big (>100mb) the upload fails with an error.

![upload_error](https://cloud.githubusercontent.com/assets/2510900/24865999/3e0c3b92-1e09-11e7-9f43-e715c53c6420.png)

# Solution
* The large rasters can be uploaded with geonode management commands which can only be done by people with server access.
* There is a timeout setting in geonode - Increase this and test
* Fix any how to make it happy

**Comment by NyakudyaA** [comment]
I have just managed to upload a shapefile that is 146 MB. Will try the rasters and close if successful

**Comment by gubuntu** [comment]
so far the management command option always words when uploads time out
