### ISSUE TITLE
Remove layer does not delete all items associated with that layer

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geonode#194]
# Problem

After uploading a layer I tried to remove it from the ui and it seems not to remove all items that have been created for the layer.    
I then tried to upload the same layer again and saw that it uses the same qgis project that has been created previously.  So it assumes because the layer name is the same.

![layer](https://cloud.githubusercontent.com/assets/2510900/25376075/3e2fafbe-29a3-11e7-91d8-a36f87ae22ed.png)

# Solution
 Delete all references to a layer

**Comment by gubuntu** [comment]
please test again @NyakudyaA

**Comment by NyakudyaA** [comment]
All records are deleted. Tested with the same layer with different extents
