### ISSUE TITLE
Create InaSAFE Headless

### ISSUE THREAD

**Issue by lucernae** [kartoza/geonode#20]
# InaSAFE Headless Draft

InaSAFE Headless is a docker container with InaSAFE inside. There are several feature requested for this:

## Features

- Should be able to run as a docker service (to calculate analysis)
- Should be able to run asynchronously and return values when it is done

## Capabilities

- Calculate analysis
- Generate report

**Comment by ismailsunni** [comment]
Please the following capabilities:
- [ ] generate a report
- [ ] read keywords from a layer (currently, I copy-paste the inasafe's code the geosafe)
- [ ] run analysis with aggregation
