### ISSUE TITLE
Bug in layer tiling

### ISSUE THREAD

**Issue by lucernae** [kartoza/geonode#205]
This issue shows up when we view the layer or map in leaflet (so it uses tiling).
For some reason, qgis server didn't display the icon feature properly:

<img width="387" alt="screen shot 2017-05-05 at 03 29 04" src="https://cloud.githubusercontent.com/assets/831865/25723703/542bc3f0-3143-11e7-9297-7f3a89dff8f2.png">

If we zoom enough we can see the problem that QGIS didn't draw the feature if it is not in the tile.
However for some features which are barely at the edge of the tiles, it gets cropped out.

<img width="857" alt="screen shot 2017-05-05 at 03 34 14" src="https://cloud.githubusercontent.com/assets/831865/25723975/5e352e44-3144-11e7-90d1-d2436524c8fb.png">

Roads is working nicely:

<img width="825" alt="screen shot 2017-05-05 at 03 32 10" src="https://cloud.githubusercontent.com/assets/831865/25723737/78ffa1ba-3143-11e7-9fdd-aef85001e5ba.png">

**Comment by lucernae** [comment]
Apparently, related with #185

**Comment by gubuntu** [comment]
yes it is
