### ISSUE TITLE
Make sure default Layer Detail interaction is working

### ISSUE THREAD

**Issue by lucernae** [kartoza/geonode#206]
When you go to Layer Detail as admin, you will be presented with this buttons:

<img width="402" alt="screen shot 2017-05-05 at 19 14 01" src="https://cloud.githubusercontent.com/assets/831865/25745003/1171c012-31c7-11e7-8426-b63737de5e62.png">

What doesn't works:

- [x] Edit Layer > Styles (empty options?)
- [x] Edit Layer > Thumbnail Set (not working)
- [x] Edit Layer > Layer Edit Data (mistakenly redirected to Map)
- [x] Edit Layer > Layer Remove (not working)

**Comment by lucernae** [comment]
Update: Layer Remove is working, it's just that it is a scheduled remove, apparently.

**Comment by lucernae** [comment]
Proposed update:

- Hide Layer Edit Data, the UI is too difficult to implement in current timeframe
- Thumbnail set will set the thumbnail according to current view extent
- Edit Styles will be just a regular qml upload.

**Comment by lucernae** [comment]
Layer > Edit Styles proposed interaction:

CC @gubuntu @NyakudyaA 


![change_style](https://user-images.githubusercontent.com/831865/27639428-5f0a0ac0-5c40-11e7-829e-0e92ae0ca70e.gif)

**Comment by gubuntu** [comment]
wow @lucernae! 

Sos does it replace the qml on disk and regenerate the QGIS project and the tilecache without replacing the geonode layer?

please tick the parts of #149 that solves.

It it also means work can start on https://github.com/kartoza/QGIS/issues/18 (not this week...)

**Comment by lucernae** [comment]
> Sos does it replace the qml on disk and regenerate the QGIS project and the tilecache without replacing the geonode layer?

Yes, we have to remove the tilecache (not auto generated, but triggered by user views), and update the QGIS Project and QML on disk, but doesn't replace the layer. The user might have to "hard refresh" the browser if the legend and tiles still stuck with the old styles, because AFAIK it was using the same url.

**Comment by lucernae** [comment]
Layer > Thumbnail Set

Basically, just following Geonode-Geoserver interaction. Click set and thumbnail set to current extent.
![change_thumbnail](https://user-images.githubusercontent.com/831865/27654308-0c14610e-5c6c-11e7-877e-34b600a18d34.gif)

**Comment by Gustry** [comment]
Very nice @lucernae ;-)

**Comment by lucernae** [comment]
Close this.
