### ISSUE TITLE
Two versions of metadata being stored 

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geonode#210]
# Problem
I have used Metasearch to add a layer into geonode and I can go in and run the analysis using geosafe which implies that the layer's metadata has `Inasafe keywords` in the metadata. When I download the layer's metadata I do not see any keywords.  There seem to be two versions of metadata. The first one is associated with inasafe keywords and the other one is stored in the database.

![earth](https://cloud.githubusercontent.com/assets/2510900/25943879/a17b394e-3641-11e7-9518-64086181c71e.png)

Layer loaded in geonode
![layer](https://cloud.githubusercontent.com/assets/2510900/25943954/e012ec4c-3641-11e7-9768-a38eef1c9814.png)

Downloaded metadata
[tanzania.zip](https://github.com/kartoza/geonode/files/992604/tanzania.zip)

# Solution
Fix and allows users to download the correct metadata

**Comment by gubuntu** [comment]
@NyakudyaA please test again and comment or close

**Comment by NyakudyaA** [comment]
All metadata can be downloaded.
