### ISSUE TITLE
Upload error of files associated with metadata

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geonode#211]
# Problem
When a user needs to upload a layer with metadata, the preserve metadata tag is activated but then if you proceed with uploading the layer it throws an error.

Selected shapefiles for loading with preserve metadata
![preserver](https://cloud.githubusercontent.com/assets/2510900/25944633/4a2fafa0-3644-11e7-8298-249f3373a1a4.png)

After running the upload the following error occurs:
![error](https://cloud.githubusercontent.com/assets/2510900/25944663/6eb9160e-3644-11e7-9959-afb7b0e3106d.png)

# Solution
Give a notification to users so that they know `metadata should not be uploaded directly with a shapefile`. The metadata for the layer can be uploaded after the layer has been uploaded.

Deactivate the `Preserve metadata xml tag` when a user has selected layers with metadata on upload data

NB: In geonode 2.4 the behavior was that a user could upload data and metadata at the same time

**Comment by gubuntu** [comment]
@NyakudyaA please test and comment or close

**Comment by NyakudyaA** [comment]
Tested this and preserve metadata is now working properly
