### ISSUE TITLE
Error cant download geonode layers

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geonode#212]
# Problem
I have a layer loaded in geonode and when I try to download the shapefile I get an error:

Layer loaded in geonode
![layers](https://cloud.githubusercontent.com/assets/2510900/25946766/d206840a-364c-11e7-84cc-306d933be9e1.png)

Download error
![down_error](https://cloud.githubusercontent.com/assets/2510900/25946812/fd714d1e-364c-11e7-82eb-31c75825f770.png)

# Solution
Fix download for shapefiles

**Comment by ismailsunni** [comment]
@NyakudyaA can you try it again? I have fixed it in #239 also

**Comment by NyakudyaA** [comment]
@ismailsunni  It's working properly now. Will close now
