### ISSUE TITLE
Metadata upload error for all layers

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geonode#213]
# Problem
Uploading a metadata xml to a layer seems to have no effect. When you download the corresponding metadata it does not show the values that were specified in your uploaded metadata xml.

# solution
Fix for all layers. 

#211

**Comment by NyakudyaA** [comment]
#211

**Comment by gubuntu** [comment]
@NyakudyaA pls test and comment or close

**Comment by NyakudyaA** [comment]
I am closing this as the metadata layer is actually uploaded and is not associated with the layer. This issue is described well in #251
