### ISSUE TITLE
Remove tile download option

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geonode#214]
One of the formats offered for download of  layers is 'Tile'. Remove this as it is not a real option.

**Comment by Gustry** [comment]
Geonode upstream is also providing this link (with Geoserver so), I'm using it. Can't we find another way to provide this link? (no HTML link for instance?)

**Comment by lucernae** [comment]
I'm also confused because not all link format is provided as downloadable but gets shown anyway (with Geoserver). For example, sometimes I found GeoTiff format which is actually an API call to WCS (so, needs additional parameters).

**Comment by gubuntu** [comment]
duplicate of #47
