### ISSUE TITLE
Set thumbnail is not working for layers uploaded 

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geonode#233]
#Problem 
I have uploaded layers using management commands and no thumbnails are generated.  I can preview the layer and see the data but when I try to replace the empty thumbnail nothing happens.

No thumbnail generated on upload

![missing](https://cloud.githubusercontent.com/assets/2510900/26668411/e613a992-46a9-11e7-8d03-5f668ab45f16.png)

Layer preview
![layer](https://cloud.githubusercontent.com/assets/2510900/26668422/f462eef4-46a9-11e7-9a1d-df726442a7a4.png)

Set thumbnail

![set](https://cloud.githubusercontent.com/assets/2510900/26668432/000542ca-46aa-11e7-90b9-489a5754fb2d.png)

No thumbnail is generated.

# Solution
make it happy
#195

**Comment by gubuntu** [comment]
duplicate of #125
