### ISSUE TITLE
Implement or Hide 'Set thumbnail'

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geonode#238]
when editing a layer or map, I expect Set Thumbnail to update the thumbnail image everywhere it's used in the site (layer, map and metadata views) but it does not appear to do anything. 

It should just run the existing create thumbnail process based on the current view (layers and extent)

child of #207

**Comment by gubuntu** [comment]
@NyakudyaA please test and comment

**Comment by NyakudyaA** [comment]
This still does not work. Also, see issue #359

**Comment by lucernae** [comment]
Probably just because of CDN. I will retest this.

**Comment by gubuntu** [comment]
set thumbnail works great on layers
