### ISSUE TITLE
Make sure all QGIS Server request is using the correct BBOX

### ISSUE THREAD

**Issue by lucernae** [kartoza/geonode#259]
Due to (possible) problem I found here: https://github.com/GeoNode/geonode/issues/3109 it might turns out that we need to review again bbox usages in QGIS Server backend. For now, i already fixed some of the layer and maps bbox usage, but it might change again based on the outcome of the issue.

Also, it might be related with #241

**Comment by lucernae** [comment]
To use upstream convention we are fixing this issue in PR #328

**Comment by gubuntu** [comment]
I assume this can be closed since #328 was accepted.
