### ISSUE TITLE
Generate Links for Layer in QGIS Server backend

### ISSUE THREAD

**Issue by ismailsunni** [kartoza/geonode#26]
There are 24 links are generated when we upload a layer to geonode by using geoserver backend. 8 of them are geoserver-independent. So, we need to generate another 16 link object when we use QGIS backend.

Here the list of the links:

| No | Name | From Geoserver | Url |
| --- | --- | --- | --- |
| 1 | Atom | False | http://localhost:8000/catalogue/csw?outputschema=http%3A%2F%2Fwww.w3.org%2F2005%2FAtom&service=CSW&request=GetRecordById&version=2.0.2&elementsetname=full&id=c2170724-c4ae-11e5-914e-08002784995b |
| 2 | DIF | False | http://localhost:8000/catalogue/csw?outputschema=http%3A%2F%2Fgcmd.gsfc.nasa.gov%2FAboutus%2Fxml%2Fdif%2F&service=CSW&request=GetRecordById&version=2.0.2&elementsetname=full&id=c2170724-c4ae-11e5-914e-08002784995b |
| 3 | Dublin Core | False | http://localhost:8000/catalogue/csw?outputschema=http%3A%2F%2Fwww.opengis.net%2Fcat%2Fcsw%2F2.0.2&service=CSW&request=GetRecordById&version=2.0.2&elementsetname=full&id=c2170724-c4ae-11e5-914e-08002784995b |
| 4 | ebRIM | False | http://localhost:8000/catalogue/csw?outputschema=urn%3Aoasis%3Anames%3Atc%3Aebxml-regrep%3Axsd%3Arim%3A3.0&service=CSW&request=GetRecordById&version=2.0.2&elementsetname=full&id=c2170724-c4ae-11e5-914e-08002784995b |
| 5 | FGDC | False | http://localhost:8000/catalogue/csw?outputschema=http%3A%2F%2Fwww.opengis.net%2Fcat%2Fcsw%2Fcsdgm&service=CSW&request=GetRecordById&version=2.0.2&elementsetname=full&id=c2170724-c4ae-11e5-914e-08002784995b |
| 6 | ISO | False | http://localhost:8000/catalogue/csw?outputschema=http%3A%2F%2Fwww.isotc211.org%2F2005%2Fgmd&service=CSW&request=GetRecordById&version=2.0.2&elementsetname=full&id=c2170724-c4ae-11e5-914e-08002784995b |
| 7 | JPEG | True | http://localhost:8080/geoserver/wms?layers=geonode%3Abuilding_points&width=681&bbox=106.80642522042223%2C-6.1877371110753945%2C106.8254000718597%2C-6.1724212517828265&service=WMS&format=image%2Fjpeg&srs=EPSG%3A4326&request=GetMap&height=550 |
| 8 | PDF | True | http://localhost:8080/geoserver/wms?layers=geonode%3Abuilding_points&width=681&bbox=106.80642522042223%2C-6.1877371110753945%2C106.8254000718597%2C-6.1724212517828265&service=WMS&format=application%2Fpdf&srs=EPSG%3A4326&request=GetMap&height=550 |
| 9 | PNG | True | http://localhost:8080/geoserver/wms?layers=geonode%3Abuilding_points&width=681&bbox=106.80642522042223%2C-6.1877371110753945%2C106.8254000718597%2C-6.1724212517828265&service=WMS&format=image%2Fpng&srs=EPSG%3A4326&request=GetMap&height=550 |
| 10 | Zipped Shapefile | True | http://localhost:8080/geoserver/wfs?format_options=charset%3AUTF-8&typename=geonode%3Abuilding_points&outputFormat=SHAPE-ZIP&version=1.0.0&service=WFS&request=GetFeature |
| 11 | GML 2.0 | True | http://localhost:8080/geoserver/wfs?typename=geonode%3Abuilding_points&outputFormat=gml2&version=1.0.0&request=GetFeature&service=WFS |
| 12 | GML 3.1.1 | True | http://localhost:8080/geoserver/wfs?typename=geonode%3Abuilding_points&outputFormat=text%2Fxml%3B+subtype%3Dgml%2F3.1.1&version=1.0.0&request=GetFeature&service=WFS |
| 13 | CSV | True | http://localhost:8080/geoserver/wfs?typename=geonode%3Abuilding_points&outputFormat=csv&version=1.0.0&request=GetFeature&service=WFS |
| 14 | Excel | True | http://localhost:8080/geoserver/wfs?typename=geonode%3Abuilding_points&outputFormat=excel&version=1.0.0&request=GetFeature&service=WFS |
| 15 | GeoJSON | True | http://localhost:8080/geoserver/wfs?srsName=EPSG%3A4326&typename=geonode%3Abuilding_points&outputFormat=json&version=1.0.0&service=WFS&request=GetFeature |
| 16 | KML | True | http://localhost:8080/geoserver/wms/kml?layers=geonode%3Abuilding_points&mode=download |
| 17 | View in Google Earth | True | http://localhost:8080/geoserver/wms/kml?layers=geonode%3Abuilding_points&mode=refresh |
| 18 | Tiles | True | http://localhost:8080/geoserver/gwc/service/gmaps?layers=geonode:building_points&zoom={z}&x={x}&y={y}&format=image/png8 |
| 19 | geonode:building_points | False | http://localhost:8000/layers/geonode%3Abuilding_points |
| 20 | Remote Thumbnail | True | http://localhost:8080/geoserver/wms/reflect?layers=geonode:building_points&width=200&height=150&format=image/png8 |
| 21 | Thumbnail | False | http://localhost:8000/uploaded/thumbs/layer-c2170724-c4ae-11e5-914e-08002784995b-thumb.png |
| 22 | Legend | True | http://localhost:8080/geoserver/wms?request=GetLegendGraphic&format=image/png&WIDTH=20&HEIGHT=20&LAYER=geonode:building_points&legend_options=fontAntiAliasing:true;fontSize:12;forceLabels:on |
| 23 | **OGC WMS: geonode Service** | True | http://localhost:8080/geoserver/geonode/wms |
| 24 | **OGC WFS: geonode Service** | True | http://localhost:8080/geoserver/geonode/wfs |

**Comment by timlinux** [comment]
Hi @ismailsunni I think we definitely don't need to try to replicate all those links. Many of them are obscure formats that whilst nice to have one day, we cannot reasonably provide today / soon.

I think we should offer to serve: shp and tiles only for now (plus the 8 others provided by geocode).

**Comment by ismailsunni** [comment]
@timlinux 
Thanks for the comment. Ah yes, I remember you did mentioned that. The geonode is already created. The shp also (in my qgis_server app), and after we finish the tiling, the tiles link will be provided, easily.

**Comment by ismailsunni** [comment]
We have done for shapefile, tiles, legend, and thumbnail. We will add more later.

**Comment by ismailsunni** [comment]
Woot, I closed it accidentally. Re-open it.

**Comment by timlinux** [comment]
I think we just need WMS (raster and vector) and WFS (vectors only) and then we can close this.

**Comment by ismailsunni** [comment]
Can we use @Gustry for WMS and WFS? But it doesn't support GetCapabilites.

**Comment by lucernae** [comment]
@ismailsunni what is the status for this?

**Comment by ismailsunni** [comment]
The WMS and WFS is available now (without GetCapabilities)
But I haven't heard from @Gustry for the WCS.

**Comment by Gustry** [comment]
WCS should be here with the latest commit from the OTF-Plugin. I think I got one question from Irwan too on gitter. Will check it again

**Comment by gubuntu** [comment]
@Gustry @ismailsunni can we close this?

**Comment by ismailsunni** [comment]
I think yes. The most important one are already implemented.
