### ISSUE TITLE
Clip and Ship

### ISSUE THREAD

**Issue by cchristelis** [kartoza/geonode#263]
# Problem

We would like to allow users to select an AOI and get a clipped dataset back.

# Proposed solution

Send an​ AOI to the QGIS/GeoServer backend and return a link that the user can download this clipped data.

**Comment by meomancer** [comment]
hi @cchristelis 
is there any dataset that we could use?

**Comment by dimasciput** [comment]
What is the user flow for this in the front end?

**Comment by gubuntu** [comment]
duplicate of #150
