### ISSUE TITLE
Search functionality not working .

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geonode#281]
# Problem
The search functionality for layers is not working. 

![edit](https://user-images.githubusercontent.com/2510900/27589350-695af5ca-5b4b-11e7-866a-470a6dfae09c.gif)

# Solution
Make it happy

**Comment by lucernae** [comment]
Sorry, regression caused by @ismailsunni 's commit:
db2a1a584be33517217fd1cf5bab88fb6673af9e
It also missed my review.
I will fix it.
