### ISSUE TITLE
Thumbnails not showing for some datasets

### ISSUE THREAD

**Issue by timlinux** [kartoza/geonode#287]
Layer map widget does not zoom to map

<img width="1177" alt="screen shot 2017-06-30 at 11 21 56 pm" src="https://user-images.githubusercontent.com/178003/27754508-25ab8b3a-5deb-11e7-9315-7c89a2389871.png">

child of #457

**Comment by lucernae** [comment]
Same problem with #289 , I will take over.

**Comment by lucernae** [comment]
Reopen because auto-closed.
Please close if fixed.

**Comment by NyakudyaA** [comment]
![tand.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ba46e77953d2fd0f723be9/125516c66e82c728ace21e0d46fc959427c0cfeb9ffbb049a15ee4d67304722b2856a7737681e779ba177e510a0d4eac470c5810f8fc9b37b4f46d2ede0356b49b381d66cc2f10a4b2831abc09bf258f4c84bfbc8e4cd2a5.png)
tested and it all works
