### ISSUE TITLE
Check Layer Name

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geonode#293]
_From @boney-bun on April 4, 2017 9:8_

Part of resolving issue https://github.com/kartoza/geosafe/issues/85, we need to have some validation mechanism when a user upload a file. The first validation is checking if the similar layer name already exist on the system. The second one is checking if it is a valid layer and title name. 
We may need to agree whether a "good" layer name must include location and subject.

_Copied from original issue: kartoza/geosafe#93_

**Comment by gubuntu** [comment]
_From @timlinux on April 4, 2017 11:52_

I would take a different approach: When the user uploads a file there is no need for this filename to remain the same as the upload. So use either a UID (better) or the layer id as the base for the layer name - and just use the original layer name for display purposes.

**Comment by gubuntu** [comment]
_From @lucernae on April 5, 2017 3:1_

In geonode internal models, all where being referenced by layer name, but this is handled automatically by geonode when the layer itself where uploaded. If it is exists, they even give a suffix. The one that is used for display is called layer_title.

**Comment by gubuntu** [comment]
_From @boney-bun on July 7, 2017 8:16_

i think we should move this issue to geonode repo instead.
let me try to understand the logic first.

**Comment by lucernae** [comment]
Hi, why this is this still an issue?

Geonode already handled file name scheme. If it is already exists the filename will have a generated suffix.
The one that is used for display comes from layer_title attribute and can be filled in metadata.xml file or edited directly in geonode. If this layer_title doesn't exists, then geonode will set the layer_title from file name as default. So, this can be prevented if we put a human friendly title name.

**Comment by boney-bun** [comment]
so, can we close this ticket?
