### ISSUE TITLE
use latest django-leaflet

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geonode#295]
the django-leaflet we are using has leaflet 0.7 yet the current verions in django-leaflet upstream is 1.03. 

Is there any reason not to be tracking the latest django-leaflet? If not then we should upgrade as we need recent leaflet functionality

**Comment by lucernae** [comment]
You have my upvote on this. We just have to make sure when we upgrade, it doesn't break some custom functionality for leaflet in geonode (some other people already made contributions).

**Comment by boney-bun** [comment]
i've looked at `explore` and `create` maps on geonode.
these pages use the old leaflet as well.
we should test this pages when implementing the latest leaflet.

**Comment by gubuntu** [comment]
have you got them all using the latest Django-leaflet yet (rather than custom loads on individual pages)?

**Comment by lucernae** [comment]
Not yet on this one.
