### ISSUE TITLE
User can not download a created map 

### ISSUE THREAD

**Issue by origianlgeek** [kartoza/geonode#299]
# Problem 

When the user tries to download a created map (Download Data Layers) the site appears telling the user that there was a problem loading the page instead of downloading the map.

![download_map](https://user-images.githubusercontent.com/30115433/28119253-6f112730-6714-11e7-8b7c-4e58b821e3ec.png)

# Expected behaviour 

All the layers in the map should be bundled into a zip file for download (with their own qml files containing the same style as in the map on GeoNode as a bonus)

child of #207

**Comment by boney-bun** [comment]
related to #207

**Comment by gubuntu** [comment]
download works, but only the shp files are packaged into the zip file. All layer files must be packaged (qml,prj,shx, etc.)

**Comment by NyakudyaA** [comment]
Download works but only the .qml are missing from the zip from the download

**Comment by boney-bun** [comment]
if the layers in the map have qml, then it should be included in the download.
in your case, the layer probably doesn't have the qml.

i tried to download this map: http://testing.geonode.kartoza.com/maps/32 and it has the qml.

**Comment by NyakudyaA** [comment]
@boney-bun this doesn't work- please check http://testing.geonode.kartoza.com/maps/99

Whilst we are on the maps - The maps thumbnails are still not correct. I wonder if this was fixed somewhere or is mentioned in another ticket

**Comment by NyakudyaA** [comment]
@boney-bun Because QGIS server keeps copies of two versions of the same layer on the server. When you download the layers they should be fetched from `/usr/src/app/geonode/uploaded/layers`
rather than `/usr/src/app/geonode/qgis_layer`

**Comment by gubuntu** [comment]
@NyakudyaA why are there two?

**Comment by lucernae** [comment]
It's an old decision to store QGIS files on a separate directory. Think of it like in GeoServer, geoserver itself needs to store the layer somewhere because it's doing something with the file, meanwhile GeoNode also needs to do something with the files.

> @boney-bun Because QGIS server keeps copies of two versions of the same layer on the server. When you download the layers they should be fetched from /usr/src/app/geonode/uploaded/layers
rather than /usr/src/app/geonode/qgis_layer

You still need to take it from qgis_layer regardless. Because the style is stored in qgs project. Since we support multiple styles, it's not possible to store multiple qml styles in files, so we store it in qgs project.

**Comment by NyakudyaA** [comment]
> @NyakudyaA why are there two?

The issue is well documented here: https://github.com/kartoza/geonode/issues/274

**Comment by NyakudyaA** [comment]
> It's an old decision to store QGIS files on a separate directory. Think of it like in GeoServer, geoserver itself needs to store the layer somewhere because it's doing something with the file, meanwhile GeoNode also needs to do something with the files.

Geoserver only stored the files in one location and references them from that location.
> 
> > @boney-bun Because QGIS server keeps copies of two versions of the same layer on the server. When you download the layers they should be fetched from /usr/src/app/geonode/uploaded/layers
> > rather than /usr/src/app/geonode/qgis_layer
> 
> You still need to take it from qgis_layer regardless. Because the style is stored in qgs project. Since we support multiple styles, it's not possible to store multiple qml styles in files, so we store it in qgs project.

@lucernae  For the example layer that I uploaded,  the qml is stored in the `uploaded/layers` folder. It makes sense to store the layer style in the project but how do you download the layer with it's style.
How do you extract the qml from the QGIS project and if a layer has multiple styles I assume we expect to download all the styles or do we just worry about the default style.

**Comment by lucernae** [comment]
> @lucernae For the example layer that I uploaded, the qml is stored in the uploaded/layers folder. It makes sense to store the layer style in the project but how do you download the layer with it's style.
How do you extract the qml from the QGIS project and if a layer has multiple styles I assume we expect to download all the styles or do we just worry about the default style.

We can extract the style of course, but at the moment we don't know how to put it as a file? Do we store it as `layer.qml` (for default style) and then `layer_style_alternate1.qml` or some other conventions?
But tbh, I prefer to just send the qgs project and refactor the file path to be a relative path.

Also, I'm not clear what download map will do? Will it download all related local layers or did you choose which layer to download? Because, when you're dealing with maps, there will be qgs project for the map and qgs project for the layers itself.

**Comment by lucernae** [comment]
> > It's an old decision to store QGIS files on a separate directory. Think of it like in GeoServer, geoserver itself needs to store the layer somewhere because it's doing something with the file, meanwhile GeoNode also needs to do something with the files.

> Geoserver only stored the files in one location and references them from that location.

Forgot to comment on this. I'm not familiar with how Geoserver works, but I agree like in the original issue, we should have used the same media folder, but retain qgis_layer location for the qgs projects info.

**Comment by gubuntu** [comment]
I've updated the OP to describe expected behaviour

**Comment by NyakudyaA** [comment]
@boney-bun cc @gubuntu what was the final conclusion to this issue. Because the layers are still being downloaded without the qml.

**Comment by NyakudyaA** [comment]
LGTM @boney-bun 
![screenshot 2018-11-16 at 11 46 28](https://user-images.githubusercontent.com/2510900/48613776-54636880-e995-11e8-82f4-8e1a8cabf6f0.png)

**Comment by gubuntu** [comment]
@NyakudyaA for a map that contains more than one layer, is this working for all the layers in the map?

**Comment by NyakudyaA** [comment]
> @NyakudyaA for a map that contains more than one layer, is this working for all the layers in the map?

Yes, it is working for maps containing two or more layers.

![screenshot 2018-11-16 at 12 06 46](https://user-images.githubusercontent.com/2510900/48614933-22073a80-e998-11e8-8830-428dce89d85a.png)

![screenshot 2018-11-16 at 12 06 31](https://user-images.githubusercontent.com/2510900/48614944-2b90a280-e998-11e8-8ad1-088e17e719d7.png)
