### ISSUE TITLE
Copying existing map does not work

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geonode#303]
# Problem
After creating a map there is an option to use the map as a starting point to create another map. This is not working as it always revert to a new map instead of using the old map as a  starting base

![copy_map](https://user-images.githubusercontent.com/2510900/28406184-c5a21084-6d2f-11e7-9730-34cea4c8436c.png)

# Solution
Please fix so that a created map can be used as a template/starting base

**Comment by gubuntu** [comment]
the layers get taken through to the new map page BUT I could not add a layer. I could chooise a layer but nothing happened when I clicked Add Layer.

**Comment by boney-bun** [comment]
it seems that the layers on the testing server were not fully loaded (the testing server was in the transition period moving its rancher server to another machine).
@NyakudyaA @gubuntu could you test it again?

this is the illustration from the testing:
![copy-map](https://user-images.githubusercontent.com/4602383/31901952-64f56f4c-b84d-11e7-874b-591b136536d6.gif)

**Comment by boney-bun** [comment]
this issue has been addressed  on testing.
i suggest to close it @gubuntu
