### ISSUE TITLE
Cannot edit created map

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geonode#304]
# Problem

There is an option to edit a created map but it throws an error.
![edit map](https://user-images.githubusercontent.com/2510900/28406534-4100f67c-6d31-11e7-92ed-6a7d83e74ded.png)

# Solution
Make it happy

**Comment by boney-bun** [comment]
i think this issue has a relation to #186

**Comment by boney-bun** [comment]
related to #207

**Comment by gubuntu** [comment]
@NyakudyaA please test again and respond to @boney-bun's comments too

**Comment by gubuntu** [comment]
thanks @NyakudyaA, re the thumbnails issue please check that it's not a duplicate of one of the many other thumbnails issues
