### ISSUE TITLE
Layer upload works but render fails

### ISSUE THREAD

**Issue by timlinux** [kartoza/geonode#323]
[SouthAfrica.zip](https://github.com/kartoza/geonode/files/1291840/SouthAfrica.zip)

Using this sample dataset, the layer uploads but does not zoom properly on the map and does not render.

**Comment by timlinux** [comment]
Oh correction it is rendering now.

**Comment by timlinux** [comment]
Expecting it to zoom to the boundary like this:

![screen shot 2017-09-11 at 10 21 11 am](https://user-images.githubusercontent.com/178003/30264968-fd2eeebc-96da-11e7-8ca3-9196fea8dbce.png)

**Comment by timlinux** [comment]
Also I don't get any thumbnail for the layer....

**Comment by gubuntu** [comment]
what was its CRS? If not 4326 then it's because of #395

**Comment by gubuntu** [comment]
@NyakudyaA pls test with this sample to confirm

**Comment by NyakudyaA** [comment]
The CRS for this layer is 3410. I think python gdal is not able to recognize this projection.
![projection](https://user-images.githubusercontent.com/2510900/45117869-11944180-b157-11e8-801e-f02582ab204c.png)

The proj4 text is
```
PROJCS["NSIDC_EASE_Grid_Global",GEOGCS["GCS_Unspecified datum based upon the International 1924 Authalic Sphere",DATUM["D_",SPHEROID["International_1924_Authalic_Sphere",6371228,0]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["standard_parallel_1",30],PARAMETER["central_meridian",0],PARAMETER["false_easting",0],PARAMETER["false_northing",0],UNIT["Meter",1]]
```

@gubuntu  I think we should improve the error message reporting if gdal does not read this CRS.
@boney-bun how about
 `GDAL could not detect the CRS of your layer, please try to project to a common CRS (ie 4326 or UTM)`

**Comment by gubuntu** [comment]
@boney-bun cc @lucernae I thought the CRS fixes would handle this? It is a valid EPSG code so why is it not accepted? Maybe QGIS has it but GDAL or Geoserver or PostGIS do not. In that case the GeoNode message is fine.
