### ISSUE TITLE
Changing layer order hides one layer

### ISSUE THREAD

**Issue by timlinux** [kartoza/geonode#342]
When I toggle layer order, one always gets hidden....

![licecap](https://user-images.githubusercontent.com/178003/30780209-0285ac98-a130-11e7-8fe8-ac742450c27e.gif)

**Comment by NyakudyaA** [comment]
@timlinux  which layers did you use. I have tried this on several combinations and it's working.

**Comment by gubuntu** [comment]
This issue was moved to kartoza/geosafe#282
