### ISSUE TITLE
Use 'Data' tab properly

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geonode#348]
# Issue

Why is there a 'Data' link in the layer download section? That you have to click on to get the list of download links... 

# Solution

Remove the tree and show all download links immediately, as in the GeoServer GeoNode

**Comment by boney-bun** [comment]
looking at the code, there should be two tabs, namely `download_tab1` for viewing and `download_tab2` for downloading.
i never see the two tabs appear together.
however, maybe it's there because of a reason.
i just not sure the business logic for this.

perhaps @Gustry could make a comment as it relates to `Links`?

**Comment by Gustry** [comment]
Looking at a Geoserver instance, two tabs are there: http://staginggs.geonode.kartoza.com/layers/geonode:tmpwllgcy

It's not us who created this "data" item. Maybe we should organize better our links between these 2 tabs.

**Comment by gubuntu** [comment]
I was referring to the download dialog on demo.geonode.org (which I see is still 2.4). So maybe the tabs appeared in 2.6?

Anyway, if they are there and we have to use them I agree with Etienne that we should put our links in the appropriate tab but also auto expand them so the user does not have to guess and click again before seeing download options. 

<img width="577" alt="screen shot 2017-09-28 at 09 28 00" src="https://user-images.githubusercontent.com/496911/30946634-5d1c8526-a42f-11e7-9282-e0b8ea7ca77e.png">

**Comment by gubuntu** [comment]
OK this is the latest Tab structure (from http://staginggs.geonode.kartoza.com)

So our Data Tab should list all links automatically and not have to be clicked on to expand the list. 

<img width="583" alt="screen shot 2017-09-28 at 09 41 48" src="https://user-images.githubusercontent.com/496911/30947007-7e9adf84-a431-11e7-9e16-e78bfb99b03c.png">

**Comment by Gustry** [comment]
@boney-bun We should check what we made wrong in qgis-server backend, why it 's not open by default. I don't think we need to change the geonode code base.

**Comment by boney-bun** [comment]
agree @Gustry 
i found that the code expect the viewing tab (first tab) to be exist and make the list available by default.
#351 should fix the problem.

**Comment by gubuntu** [comment]
@boney-bun is this deployed on the testing server and did you test it there? 

btw the testing server is down

**Comment by boney-bun** [comment]
@gubuntu

**Comment by gubuntu** [comment]
passed on testing
