### ISSUE TITLE
upgrade django version

### ISSUE THREAD

**Issue by boney-bun** [kartoza/geonode#356]
# problem:
the current django version is 1.8.7.
we can't use the latest build-in decorator such as *mixins* to easily control class-based view (ex: `geonode.maps.qgis_server_view.py` or `geosafe.views.analysis.py`). 
these decorators help us to control the authentication without doing so many refactoring into the existing view functions.

# proposed solution:
upgrading current django to either 1.9 or even 1.11 seems to be feasible.

**Comment by Gustry** [comment]
I guess we should stick to the upstream geonode version. They are still using 1.8.7. https://github.com/GeoNode/geonode/blob/master/setup.py#L55.

Which feature would you like to you available only in 1.11?

If you need to do it, this should be done against geonode upstream, not our fork. Let's keep our fork as small as possible.

**Comment by boney-bun** [comment]
jump from 1.8 to 1.11 probably is a bold action.
maybe switch to 1.9 would have a slight improvement to the framework @Gustry ? 
the proposal to using django 1.9 aims to using [Permission mixins for class-based views](https://docs.djangoproject.com/en/1.11/releases/1.9/) decorator in the geosafe. 

if we could successfully deploy the new version to our project, there is a chance we could ask the upstream to do it too :)

**Comment by lucernae** [comment]
I actually agree with @Gustry . Even if they want to upgrade to 1.9, we should do that in upstream first.
It would be troublesome to merge the changes later.

**Comment by ismailsunni** [comment]
Jumping here. +1 also to upgrade it in upstream. i.e. make another branch from upstream, upgrade, make a PR, then after merged we update it from upstream. Merging too much code is not easy :D

**Comment by Gustry** [comment]
Maybe discuss first on the geonode dev list if we really need that.

Note that Django 1.11 is an LTS, so better to update to that one.

**Comment by gubuntu** [comment]
This issue was moved to kartoza/docker-geosafe#110
