### ISSUE TITLE
Issue for the UI

### ISSUE THREAD

**Issue by lucernae** [kartoza/geonode#36]
- [x] Error messages when user is not logged in
- [x] Tooltip for the flower image/header that says that it will go back to geonode/home page
- [x] Keep the triangle when selecting layer to stay in the position
- [x] 1:2.5million scale is the smallest to create analysis. tell user to zoom in if the scale is smaller
- [ ] Use geonode search API to filter layers and provides search box. It will list filtered layer.
- [x] Use visual cues for category when:
      - don't highlight when there is no layer on it. Just popup a message that there is no layer available. Add a button in popup to redirect user to upload page.
      - If there is only one layer available then we should highlight it on hover, and if selected, put a ring highlight and show popup message. Don't show triangle.
      - When there are more than one layer, we show triangle and on hover
      - Give accent color to differentiate no layer, selected, and hovered.
      - Show selected layer in status bar
- [x] Dismiss the popup for whatever button or map you click after selecting a layer.
- [x] Give a link to List Analysis page from the report area (Show previous analysis)
- [x] Tell the user that the dialog will be closed automatically (show a spinner/throbber loading). It should be a modal dialog nonclosable. 
- [ ] It would be nice to poll the status of the task using websocket
- [x] Create an impact card to show impact layer summary (don't mind the chart for now, just show the hazard and exposure icon, and button to show report, download and save.
- [x] Group the show report buttons in the impact category.
- [x] Fill the impact category with analysis impact. Use green visual cues for the show report button below impact category to show that it is available. Click show report button to show again the impact card.
- [x] Need some new icons for Impact, Impact Function and Show Report Button category.

# Papercut
- [x] Give padding for the item in the list of category
- [x] Show meaningful names for the impact layer list, for example from the layer title.
- [x] Change List Analysis to Analysis List in Geosafe Menu
- [x] Add a date and user column in List Analysis.
- [x] Change Impact Function ID to Impact Function Name.
- [x] Change Detail column to view, and use it to show Map or the Report
- [x] Add also download Column to download all the zipped impact and pdf
- [x] Change Keep column to Save and delete the "Layer is" text. Make the toggle like: http://cssdeck.com/labs/ldmtsmfk
- [x] Add a button for Filter by only user analysis or all analysis

**Comment by timlinux** [comment]
Moving the two remaining tasks to separate tickets in the backlog
