### ISSUE TITLE
fix testing urls

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geonode#363]
After changing staging.geonode.kartoza.com to testing.geonode.kartoza.com, thumbnails and possibly other content is not working.

Update urls to make everything work again.

**Comment by boney-bun** [comment]
i think this is no longer an issue.
could we close this?

**Comment by gubuntu** [comment]
@boney-bun close if you are sure it is not longer an issue, with a comment on how you are sure.

**Comment by NyakudyaA** [comment]
When one changes domains or content geocode provides a management command to update all resources to the new domain

`python manage.py migrate_baseurl` should do the trick for all resources
