### ISSUE TITLE
Issue related with PR to upstream

### ISSUE THREAD

**Issue by lucernae** [kartoza/geonode#378]
I've done some code review for our next PR to upstream GeoNode stage 3 (PR with all qgis_server modules in it).

There are a couple of issues that needed to be check, still. I need @boney-bun to confirm the following issues:

- [x] GeoServer should not have QLR related functionality. QGIS Server should have this (either in layer or maps). Please check if there are still any codes that assumes that GeoServer needs to support QLR. I already deleted a couple of them, but I'm not sure if is there anything else. Check on `geonode.maps.urls` and `geonode.maps.views` to make sure that my fix is working on QGIS Server.
- [x] Static files development should follow guidelines from GeoNode team. JS Libraries that exists in bower should be installed and described in bower and grunt file. We should not include it as seperate files, for example `clipboard.js` and `easy-button.js`. Instead we minified it using grunt into `assets.min.js` and `leaflet-plugins.min.js` (they want separate minified file because some people didn't use leaflet). I already made necessary changes (include dependencies in bower and grunt, and recompile minified css and js), but please check that your implemented functionality still works. For staticfiles development. Make sure you delete your geonode/static folder before doing checkout so it will not contains leftover files.
- [x] I'm kind of out of loop with Maps functionality. Can you explain what GeoNode previously supports, like `map_embed` or `map_embed_widget`? We need to know which one is only for QGIS Server (like QLR one) and which one already exists in GeoNode, and which one we made but potentially not exclusive for QGIS Server, like download map leaflet might be provided for GeoServer and QGIS Server. Also does these functionality complete yet (with unittests)?
- [x] I found some dictionary key in maps (or maybe layer) context called `show_popup` what does it do?

For reference, you can check the branch that I'm currently working on for upstream changes in `qgis-server-pr-3` branch. You can checkout to that branch to check it.

# Reference

Documentation for doing static development can be seen here (step 7):
http://docs.geonode.org/en/master/tutorials/devel/devel_env/index.html
Ping me if you're confused. The documentation indeed is slightly confusing.

CC @gubuntu 

child of #457

**Comment by boney-bun** [comment]
I think most of these issues have been resolved by @lucernae himself when upgrading to geonode 2.8. except for `easy-button.js`, i need to confirm again once we can fully use geosafe module. 
`show_popup` is used in the layer detail page. the variable is basically a flag to distinguish either a user clicked on **layer detail** or **download layer** link. if the latter, the `Data` tab will automatically be chosen in **Download Layer** window. without this variable, the user will need to eventually clicked on the `Data` tab.

**Comment by lucernae** [comment]
We have already merge this PR long ago.
Thanks everyone!
