### ISSUE TITLE
shapefile download gives 502

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geonode#389]
on geonode.bnpb.gov.id

**Comment by boney-bun** [comment]
not valid anymore.

i can download zipped shapefile without any problems.
suggest to close this issue
![kartoza-geonode389.gif](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58cac11cd032f92000868ac7/125516c66e82c728ace21e0d46e39588378d99a8c2eeba4caa52f4917a1e7e316546b3397f8fe62bab0021435a5a1aae14515d40fefadc23a2e03c268a5c58b8d5385e70d42103eee9dc4be05ce36ade0d97bcae8b44cae93824e0838b4b371b041d8aff4f78.gif)
