### ISSUE TITLE
Fix QGIS layer download text

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geonode#390]
Maps download says 'QLR layer' It should say 'QGIS layer file (.qlr)'

Check and fix in Map download and in Layer download

**Comment by boney-bun** [comment]
I think this issue no longer valid.

On layer download:

![Screen Shot 2018-02-05 at 11.47.48 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58cac11cd032f92000868ac7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216454f66b7191a379ee0c2f56415b46bc21254d58eeb9cb74fce36f34985619e8d4395d21cf3f15aebbd717bb57ba768b4fd6e3b8df4dc4fa2137a5dad11b61435c52dcbd4f3fb29b49c259f34ae64551ad113f67e775366e0a.png)

On map download:
Do we want to add **(.qlr)** on the map download?

![Screen Shot 2018-02-05 at 11.47.17 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58cac11cd032f92000868ac7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216454f66b7191a379ee0c2f56415e49bc21254d58eeb9cb74fce36f34985619e8d4395d21cf3f15aebbd717bb57ba768b4fd6e3b8df4dc4fa2137a5dad11b61435c52dcbd4f3fb29843c259f34ae64551ad103764e1723f6e0a.png)

**Comment by gubuntu** [comment]
@boney-bun the layer functionality looks OK but look carefully, the Map one is not fixed as per the OP, so please fix it.

**Comment by gubuntu** [comment]
@boney-bun  the procedure is a tester (me in this case) closes once they are happy that it is working on the testing server (which it isn't yet)

**Comment by gubuntu** [comment]
LGTM
