### ISSUE TITLE
two basic map functionality don't work properly

### ISSUE THREAD

**Issue by boney-bun** [kartoza/geonode#394]
# Problem

deploying the latest to testing server, here are what I found:
- clicks **embed map**, then choose  **embed iframe link**. 
copy the snippet on a text editor, save as a html file. 
loads the html file in the browser. 
the result is all layers will be rendered instead, not specifically for the chosen map. 
- thumbnail doesn't change after editing a map or **set thumbnail** button is clicked.

# Solution:
- The html file should show only the layers within the map, not all layers.
- thumbnail should be updated after editing a map and **set thumbnail** button is pressed.

**Comment by gubuntu** [comment]
@boney-bun move comments from your first item to #253 and then close this.

the set thumbnail is a completely different issue so should be in it's own ticket - and it is in

**Comment by boney-bun** [comment]
done @gubuntu 
i'll close this this ticket.
