### ISSUE TITLE
[GeoNode] Projection issue in the layers

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geonode#395]
_From @felix-yew on January 11, 2018 9:33_

### Problem
When we finish upload some layers that have projection in geographical (EPSG:4326), ie jakarta_flood_18113_wgs_no_kw's layer, we can see that the layers can show in list of layer, especially in the thumbnail view that can directly show the type of layer. Then, it will different if we upload some layer with the differerent projection (in addition to EPSG:4326), ie UTM zone 49s, we find a problem to see the thumbnail view. In the list of layer, we can see that the Jalan_Sleman_49s's layer do not have a thumbnail view in the fixed view. See the image below:
![image](https://user-images.githubusercontent.com/13621886/34814961-235786a0-f6e2-11e7-8076-6dce0bacc85c.png)

Let see the different layer with the different projection, in the image below:
![image](https://user-images.githubusercontent.com/13621886/34815934-d9982a20-f6e5-11e7-9349-08404066debc.png)

When we check it in the metadata details, there have a different between them. 
![image](https://user-images.githubusercontent.com/13621886/34816447-8dbb0aee-f6e7-11e7-9b1c-c6cfe5e26ebc.png)
In this case, in the left side, maybe it is same explanation like map view. I think the layer shown but in the very small size. And when we see the layer extent look strange because the Projection System indicate that the layer in EPSG:4326 but why the layer extent show the different format (metres). This case also appear in the list of layer thumbnail preview.
In the right side, the extent layer show accordance with the Projection System. So the layer can directly show in the map view.

I assume that:
1. Maybe the layer in the map view not shown because have the different extent layer. The layer maybe appear, but because of extent layer have a wide coverage so the layer look very small and it as if no image in the thumbnail view.
2. We can see in the metadata details that the extent layer in the left side like in metres UTM's format but the projection system is in EPSG:4326. 
The question is: 
Do uploading layer into the geonode will change or transform coordinate to EPSG:4326? If yes, maybe the coordinate transformation also included the extent layer (ie. from metres/UTM to geographic coordinate)

### Expected Behaviour
If the CRS of layer need to transform into the WGS84 projection, it will better if the extent of layer also transform into the geographical coordinate.

### Environment
geonode.inasafe.org

### Proposed Solution
Make it happy.

@samnawi @adissadis @lucernae @gubuntu 

_Copied from original issue: inasafe/inasafe#4856_

depends on #437
child of #457

**Comment by gubuntu** [comment]
- one should be able to upload a layer in any CRS that QGIS can handle
- the layer should stay in that CRS in its backend storage and be described with the correct CRS in its metadata
- QGIS will then correctly serve the layer in whatever CRS is requested (e.g. 3857 for web maps) 
- Thumbnail requests should work correctly if the CRS is properly defined in the metadata

**Comment by gubuntu** [comment]
@felix-yew for the layers that are not in 4326, where are they getting 4326 in their metadata? Is the QGIS user (you?) doing that or is the system applying the wrong CRS in the metadata during upload?

**Comment by lucernae** [comment]
mas @felix-yew did you upload the layer with metadata? The metadata needs to be consistent with the actual CRS (and also the extent inside the layer).

**Comment by adissadis** [comment]
This problem appear when we tried to upload layer in UTM format. The layer originally have CRS UTM 49S. As shown in this image:

![image](https://user-images.githubusercontent.com/2520159/34857364-ee4e860c-f77c-11e7-85f7-4bf641eb6a59.png)

Where we get the CRS?
By using right click on the layer -> Save as -> Create new layer with CRS: UTM 49S (EPSG: 32749)

**Comment by adissadis** [comment]
Me and @felix-yew just tried with the data that already stored in Geonode InaSAFE (Jakarta_District_WGS84):
http://geonode.inasafe.org/layers/geonode:jakarta_district_boundary_wgs84

Download it -> Open in QGIS -> Save as new layer with new CRS (UTM 49S) -> Upload to geonode

And i got same problem with the other layers. the thumbnail is missing and it become WGS84 in metadata:
![image](https://user-images.githubusercontent.com/2520159/34858158-3e4c15ee-f781-11e7-8b09-1981edf029d8.png)

I already check the metadata in qgis and it originally in UTM 48S:
![image](https://user-images.githubusercontent.com/2520159/34858166-4f55f0f8-f781-11e7-80d3-d7ba7e167e2a.png)

So i think Geonode tried to change the projection to EPSG 4326 where the data itself in EPSG 32748 (UTM 49S)

**Comment by felix-yew** [comment]
Hi @gubuntu - thank you for response this issue. Actually this issue find by mas @adissadis when upload some material training to geonode. And, then he asked me about this issue, so I try it by download the layer then check it in QGIS for the actual projection, (and I am sure that the file is in UTM). 
> @felix-yew for the layers that are not in 4326, where are they getting 4326 in their metadata? Is the QGIS user (you?) doing that or is the system applying the wrong CRS in the metadata during upload?

Like mas Adis said, we only upload the original layer (with UTM projection). So, I guess the geonode change only the projection system without the extent layer to EPSG:4326.

> mas @felix-yew did you upload the layer with metadata? The metadata needs to be consistent with the actual CRS (and also the extent inside the layer).

yes mas @lucernae - we also upload the xml file with the original file.

**Comment by gubuntu** [comment]
Sounds like a bug

**Comment by lucernae** [comment]
Can you share the file so I can check it later mas @felix-yew?

**Comment by felix-yew** [comment]
mas @lucernae you can try by download one of the layers with other EPSG:4326, ie. http://geonode.inasafe.org/layers/geonode:krb3_49s (this layer in UTM projection).

**Comment by adissadis** [comment]
Here's some example: 
[Jalan_Sleman_49S.zip](https://github.com/kartoza/geonode/files/1630697/Jalan_Sleman_49S.zip)

**Comment by gubuntu** [comment]
confirmed as a bug with that sample data set. 

GeoNode or QGIS is not respecting the CRS of the layer and assumes it is 4326.

**Comment by gubuntu** [comment]
possibly related: https://github.com/GeoNode/geonode/issues/3593

**Comment by capooti** [comment]
This is known bug, yes #3482

**Comment by NyakudyaA** [comment]
@gubuntu  from my investigation yesterday I noticed the following:
* The qgis project that is generated on the fly by otf-plugin has the layer with a projection properly defined. I could open the project in QGIS.
* The otf-plugin generates a project that does not have any layer extent information in it so I assume some function is doing this. (When you open the project in QGIS you actually have to zoom to layer extent to render the layer in canvas)
* When QGIS server makes a request what projection does it request for a layer and the extent. We cannot assume the projection for a layer is always 4326. When the layer's projection is metres it needs to be handled properly.
* I assume all tiles are being generated as 4326 and thus having the wrong extent.

**Comment by gubuntu** [comment]
#411 related

**Comment by gubuntu** [comment]
fix this while fixing #289

**Comment by boney-bun** [comment]
i think this problem has been solved.
Jalan Sleman (EPSG:32749)  can now be loaded properly into testing server.

**Comment by gubuntu** [comment]
maybe, but there's no thumbnail

**Comment by boney-bun** [comment]
the missing thumbnail is because i was testing #426
i'll do the testing by created another one so it doesn't mix up.

for testing purpose, i've just uploaded the new one: http://testing.geonode.kartoza.com/layers/geonode:jalan_sleman_49s

**Comment by NyakudyaA** [comment]
the layers can be loaded even with different CRS geographic or meters
![crs.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ba46e77953d2fd0f723be9/125516c66e82c728ace21e0d46eb868961cec1b99de6b546a749b2ce6b137f727b00fb2d7481b22dea472b040d5f4eaa155f0b40f9eb9539e4e76224d50152a7842f4d7ed43f10a6b9871cb704bf268b4e83b6be8d5e8d.png)
