### ISSUE TITLE
[GeoNode] Failed to update metadata by upload the xml file

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geonode#396]
_From @felix-yew on December 21, 2017 6:9_

### Problem
When I try to update the metadata in geonode.inasafe.org through `Edit Layer` - `Upload Metadata` and then upload the xml file for the related layer files. But, when the process upload done, I do not get the results uploaded because I see the metadata is empty instead. Although I have completed the previous metadata in QGIS before I upload it into the geonode.
This is the picture of layer before I upload the metadata:
![upload metadata before](https://user-images.githubusercontent.com/13621886/34240939-649f9bf6-e644-11e7-8bad-d175fd68b843.png)

After done, I check the layer but the result was not as I expected
![upload metadata after](https://user-images.githubusercontent.com/13621886/34240971-9909c0b0-e644-11e7-8c74-2c354c0118e7.png)

I have edited to complete the metadata with MetaTools in QGIS.
![metadata viewer](https://user-images.githubusercontent.com/13621886/34242741-bbc28820-e64f-11e7-8d28-649b43dc681d.png)

Is there any step that I miss? or maybe for upload the metadata need another file, besides the *.xml file?

### Expected Behaviour
geonode can read the xml file and can update and fill the metadata as the user wants

### Environment
geonode.inasafe.org

### Proposed Solution
make it happy

Cc: @lucernae 

_Copied from original issue: inasafe/inasafe#4823_

child of #457

**Comment by lucernae** [comment]
I'm aware of this issue, but still haven't got time to investigate it.

**Comment by gubuntu** [comment]
@lucernae this is critical for INGC - @raisserafael  tried uploading metadata with v4 keywords yesterday on the new production upgrade and while the upload appeared to work, the layer detail page now fails. 
![Layer_Info.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ba46167953d2fd0f723be0/125516c66e82c728ace21e0d46c495832690bc8081efb001e81fe086264c22703d46f96925dde27abb1a7d050b5e1ba914580a16fcf98f7fa1e23875984019af80330b2b9b645bf9fa9015ad00bd2a8a4a86b0b48848c5e13824e5889d02.jpg)

![Upload_metatada_error.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ba46167953d2fd0f723be0/125516c66e82c728ace21e0d46dd84962c83879682ecab42b05cf495164335612616e1673295f127b54778154d555ca949095d10f4afdd7fa7e339258a0959edd16b0b73923914bea4905dee5fee7fd616cfe3fe9846d2e9352fe68e8c49361c011e8df95f30a18b06.JPG)

**Comment by NyakudyaA** [comment]
I will close this ticket. If will describe the procedure here on how to get proper keywords recognised.

* Upload layer in Geonode - No metadata added
![upload](https://user-images.githubusercontent.com/2510900/46593639-f73ee200-cacd-11e8-80a3-e927c1c09e1f.png)

* Navigate to the newly created layer and notice the keywords that have been generated
![places-metdata](https://user-images.githubusercontent.com/2510900/46594061-15f2a800-cad1-11e8-8f38-af5b4a480f1f.png)

* Now open your metadata XML in a text editor and modify it slightly to include the identifier.
![new_metadata](https://user-images.githubusercontent.com/2510900/46594193-ac26ce00-cad1-11e8-8e96-ecf19418c422.png)

* Edit the layer in Geonode and upload the metadata
![pop-update](https://user-images.githubusercontent.com/2510900/46594222-ded0c680-cad1-11e8-881e-13c70e36081c.png)

* Now proceed to look at the metadata preview and other tags
![updated](https://user-images.githubusercontent.com/2510900/46594233-058efd00-cad2-11e8-808a-35c115e38246.png)

cc @lucernae
