### ISSUE TITLE
Add GeoJSON support in Geonode

### ISSUE THREAD

**Issue by Gustry** [kartoza/geonode#405]
For the migration of the Realtime platform, we need to upload layers from InaSAFE to Geonode.

Since InaSAFE v4, InaSAFE is using geojson because we can have long file names.

But it's not supported by Geonode:
<img width="679" alt="screen shot 2018-02-13 at 09 21 05" src="https://user-images.githubusercontent.com/1609292/36136002-583db8b8-109f-11e8-89e2-c62ff28cd5dd.png">

Need to do a similar work after the ASCII support: https://github.com/GeoNode/geonode/pull/3105

**Comment by myarjunar** [comment]
We need to implement this as GeoSAFE is already using InaSAFE v4

**Comment by boney-bun** [comment]
since every layers should have .qgs file in qgis-server perspective, i'm wondering what happen when a user uploads a geojson?
do we need to convert the geojson into shapefile for the qgis-server backend?
also, do we need to create a .qgs file for the geojson?

**Comment by boney-bun** [comment]
thanks for your comment @Gustry 
so i manage to enable the geonode accepts the geojson format locally (thanks to @lucernae for the hints). 
the problem now is there's no thumbnail for the geojson layer and no layer shows up in the layer detail.
it seems that the geonode still doesn't know what to do with the geojson format (other than adding the geojson info to the db).

cmiiw,  the geojson format aims to be embedded in the webmap. 
hence, geojson format is  very simple, no other files required.

the problem with geonode and qgis-server is we need to store the layers (in this case: analysis layers)  for other purposes too. 
do you think we need to transform the geojson into shapefile?
i'm still figuring out what to do to geojson in the backend.

**Comment by Gustry** [comment]
Geojson is THE file format 😉 

Just keep geojson in the backend. We use it a lot in InaSAFE: https://github.com/inasafe/inasafe/tree/develop/safe/test/data/gisv4/exposure Look how many geojson file we use.

Don't transform it to shapefile. We don't want shapefile (limited field names, many files etc) and it's exactly why I wanted to support geojson in geonode. @ismailsunni added some logic to convert geojson to shapefile to overpass this issue. It would be much better to avoid this transformation. InaSAFE v4 is very not friendly with shapefile

**Comment by NyakudyaA** [comment]
Json files are now being stored in the backend if you upload one
![json.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ba46e77953d2fd0f723be9/125516c66e82c728ace21e0d46e287952dc0cfeb9ffbb049a15ee4d67304722b2856a7737681e779ba177e510a0d4eac470c5810f8fc9b37b4f46d2ede0356b49b381d66cc2f10abb2831abc09bf278a4b85bebc884dd2a5.png)
