### ISSUE TITLE
Map view cosmetic improvements

### ISSUE THREAD

**Issue by timlinux** [kartoza/geonode#41]
- [x] Change  'List layer' to 'Available layers'
- [x] Change layer list combo to show friendly layer names, not file names
- [x] Add remove button next to each layer in the layer list so that it can be removed from the map after adding it
- [x] Put some padding above 'Add layer' and remove colon after 'Add layer:' 
- [x] When the first layer is added, zoom to the extents of that layer
- [x] QGIS map layers need transparency
- [x] Need ability to save a map and return to it later

**Comment by timlinux** [comment]
Here is my mockup of what the map view should look like:

<img width="927" alt="screen shot 2016-05-06 at 11 19 56" src="https://cloud.githubusercontent.com/assets/178003/15070391/39bdfba6-1384-11e6-8358-feb9326dff0a.png">

**Comment by ismailsunni** [comment]
I have implemented the functional side of this ticket. But I need help from @MariaSolovyeva to make it prettier.
