### ISSUE TITLE
Unable to render the layer properly with usable extent

### ISSUE THREAD

**Issue by vasuse7en** [kartoza/geonode#411]
I am trying to use a shape file layer which was created using arcgis, it wont render properly till i zoom into that extent, inital view will the whole globe three times, when i zoom to particular point the layer will be displayed, and now if i want to run analysis on geosafe nothing will happen
1) Geonode layers list
![image](https://user-images.githubusercontent.com/16218127/36593735-051a40aa-18c1-11e8-8fbc-6fc5d36a835a.png)
2) When I opened the layer
![image](https://user-images.githubusercontent.com/16218127/36593787-3c7f2ea2-18c1-11e8-9577-a0867b3feab0.png)
3) When i zoomed into one of the three points
![image](https://user-images.githubusercontent.com/16218127/36593802-4e069c8c-18c1-11e8-95b7-3b6c5c0b4bf8.png)
4) Now i go to create analysis page the layer is displayed
![image](https://user-images.githubusercontent.com/16218127/36593825-650d5d9e-18c1-11e8-9731-2272bd2f9094.png)
5) Now when i select the layer the screen will be blank with error message no usable extent
![image](https://user-images.githubusercontent.com/16218127/36593859-8a30b526-18c1-11e8-94d9-a1b3e528028a.png)

When I open the layer in QGIS it works fine
![image](https://user-images.githubusercontent.com/16218127/36594113-d20536b4-18c2-11e8-96be-b6c554cffac9.png)

Am attaching the zipped file of layers
[roads.zip](https://github.com/kartoza/geonode/files/1751631/roads.zip)

**Comment by NyakudyaA** [comment]
Thanks for reporting this. This is a known issue https://github.com/kartoza/geonode/issues/395. It's mainly a projection issue. In the meantime, you could try to reproject your layer to CRS:4326 in  QGIS and use that in Geonode.

**Comment by gubuntu** [comment]
@NyakudyaA please test and update the status of this

**Comment by NyakudyaA** [comment]
This has been fixed.  Added a layer with UTM 33S and it sits in the correct position.
![utm](https://user-images.githubusercontent.com/2510900/45117562-3e942480-b156-11e8-8d27-9fc1467c34d7.png)
