### ISSUE TITLE
List of issues found when updating from master.

### ISSUE THREAD

**Issue by lucernae** [kartoza/geonode#414]
This applies for upstream geonode 2.7.x branch (2.8 wannabe).
The changes in geonode 2.7.x makes it rather difficult to provide a stable build for our GeoSAFE/GeoNode related build. I suggest that we fix this ASAP before GeoNode team include further changes. This is also important so we can PR bugfix for our QGIS Server backend in upstream. The current one is broken.

The issues found so far (might increase as I dive along):

- [x] Change in geonode docker build. Now they use base `geonode/geonode:latest`. Still using onbuild trigger, but the resulting built image now named `geonode/geonode:latest` too. This is described in docker-compose.yml (image key)
- [x] Issue with image build because pip needs to be upgraded, the onbuild trigger will fail because pip was not updated. Maybe we need to submit PR for upstream geonode docker image, so this won't happen again.
- [x] Refactored settings name broke local_settings.qgis.sample. Need to fix it to increase coverage. Related settings called MAP_BASELAYERS and PUBLIC_GEOSERVER (previously LOCAL_GEOSERVER)
- [x] `geonode.qgis_server` is enabled by default by geonode team. Possibly because of a decreased coverage caused by broken local_settings.qgis.sample. We need to disable this to avoid issues with GeoServer.
- [x] Refactored architecture of map client library. They now uses Class hooks. Because no one test it, Layer and Map details is broken in leaflet. Related settings that needs to be refactored for leaflet is: `GEONODE_CLIENT_LAYER_PREVIEW_LIBRARY` and `GEONODE_CLIENT_LAYER_PREVIEW_LIBRARY`
- [x] I'm able to fix Layer detail view so far, but Map detail view is still broken.

cc @gubuntu @boney-bun 

child of #457

**Comment by gubuntu** [comment]
all complete
