### ISSUE TITLE
Metadata detail field name error

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geonode#418]
_From @gubuntu on January 22, 2017 11:2_

'Projetion System' is spelt incorrectly on the metadata detail page. In any case it should rather be 'Coordinate Reference Sytem'.

_Copied from original issue: kartoza/geosafe#35_

child of #457

**Comment by NyakudyaA** [comment]
@boney-bun  upstream Geonode refers it to `Projection System` I think if we change it to `Coordinate Reference System` we should do a PR upstream for this.

**Comment by NyakudyaA** [comment]
this has been fulfilled as noted below:
![screenshot 2018-10-09 at 13 31 47](https://user-images.githubusercontent.com/2510900/46666740-be833380-cbc7-11e8-80c9-ac2de83812b7.png)
