### ISSUE TITLE
define a skin for INGC

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geonode#420]
work with Jose and other stakeholders to establish a look and feel for 
- http://geonode.ingc.gov.mz and
- http://geonode.kartoza.com

@lucernae can you retrieve the skin we did a couple of years ago for http://geonode.inasafe.org/ and apply it there?

then implement if you can or hand over to a dev that can

depends on https://github.com/kartoza/docker-geosafe/issues/120  for deployment but design can proceed already

child of #458

**Comment by carina1000** [comment]
Hi @gubuntu - Do we want a look and feel that is different to what we can see already? All the colours, fonts, etc? For http://geonode.ingc.gov.mz?

Then, http://geonode.kartoza.com isn't responding!

Is it a style guide that I should build? Are there colours, logos etc that are already set? Could I get these please?

**Comment by gubuntu** [comment]
@raisserafael please get some inputs from INGC regarding their corporate image (colours, logos, fonts etc) and desired layout and content.

**Comment by carina1000** [comment]
hi @raisserafael  please let me know when you're available to discuss the above?

**Comment by raisserafael** [comment]
@carina1000  I will have the final meeting tomorrow with INGC to get some inputs regarding their corporate image (colours, logos, fonts etc) and desired layout and content. back to you when all set up.

**Comment by gubuntu** [comment]
please share mockups asap

**Comment by carina1000** [comment]
# Problem

We need to reskin GeoNode with INCG colours

# Solution

[GeoSAFE_Geonode.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a533a594304490012b9cfb6/125516c66e82c728ace21e0d46cf919510a3a58cb0ceba4caa52f4916b0a65633b0ba92e7391a172fd1723005d0b46fa150c5e11f9ac897ef4b63c76de5b5fe9d47f4366846c4ff8e7df46f554f832815d84b1b68b49c3ef3926e58a8a4e361a040ac4.pdf)

I have put all the assets you'd need into this folder: https://drive.google.com/drive/u/1/folders/1yL2_ZFT30Trf2f2j89LdSmIlAIIomECL?ogsrc=32

I would like to call and talk to you before you start implementing these designs!!

**Comment by carina1000** [comment]
Document colours:

- Dark Green: #1A6C38
- Green: #2AA858
- Orange: #F6A623

**Comment by carina1000** [comment]
I have added the disclaimer text to the mockup - please see FINAL mockup:
[GeoSAFE.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a533a594304490012b9cfb6/125516c66e82c728ace21e0d46cf919510a3a58ccda5fd53b652fa912a5265296b51fb2a2281bb2ebb462a045a0a4ef913585f42a8fedd2fa3a42062c80d55b98e30063e937f03a6aa801eb500bf238c4680b0be8b49c1e93f37aa.pdf)

**Comment by boney-bun** [comment]
@carina1000  are we going to allow a user to choose preferred language? since i can't find it in the final mockup.

**Comment by boney-bun** [comment]
> https://drive.google.com/drive/u/1/folders/1yL2_ZFT30Trf2f2j89LdSmIlAIIomECL?ogsrc=32

hi @carina1000 could you give me access to your folder

**Comment by boney-bun** [comment]
the 2 PRs in action:
![geonode 420](https://user-images.githubusercontent.com/4602383/46453745-4b477f00-c7cd-11e8-9a73-592e14a1a29d.gif)

@carina1000 we might need to change the top navigation and footer as it will not be obvious in other pages (for example: layer list page).

**Comment by gubuntu** [comment]
@boney-bun @carina1000 the INGC skin needs to be in English and PT. i18n must work (detecting user locale) and switching between languages must be seamless.

**Comment by carina1000** [comment]
You are right @boney-bun - I'd like to suggest that we change the bar colour to grey #4A4A4A
![screen shot 2018-10-04 at 11 54 55](https://user-images.githubusercontent.com/35214829/46466743-5ea61a80-c7cc-11e8-877e-cc7d6a8c0bfd.png)

**Comment by gubuntu** [comment]
@boney-bun please work with @lucernae to ensure the theme gets into the ingc theme repo and is applied asap in INGC production, then move to testing

**Comment by boney-bun** [comment]
@gubuntu the new repo is here: http://github.com/kartoza/ingc_geonode_theme/
it is a private repo. do you want me to make it public?

i'm moving all works from the last PR into this repo.

**Comment by boney-bun** [comment]
@gubuntu it's public now.

new landing page in the repo:
![newingclandingpage](https://user-images.githubusercontent.com/4602383/46601270-cafb8380-cb16-11e8-9eb7-3ae07ba165df.gif)

**Comment by gubuntu** [comment]
great @boney-bun please deploy to INGC asap

**Comment by NyakudyaA** [comment]
The Skin is deployed and all looks good

**Comment by gubuntu** [comment]
Feedback from WB:

The landing page needs a big polish ASAP:
- align all text
- consistent fonts
- Correct case (e.g. fix 'Realistic Natural Hazard Impact analysis')
- change 'InnaSAFE made easy' to something more meaningful like  'contingency planning made easy'
- improve contrast between text and background
- 'What can it do' is not translated
- consistent dropshadow (or not)
- general design polish

**Comment by boney-bun** [comment]
the changes (apart from what i have ticked in @gubuntu comment):
- all headings have shadow
- text don't have shadow
- all are justified alignment
the https://github.com/kartoza/ingc_geonode_theme/pull/14 in action:
![screen shot 2018-11-06 at 10 47 54 am](https://user-images.githubusercontent.com/4602383/48041829-9d573800-e1b1-11e8-9478-37253ed6abef.png)
![screen shot 2018-11-06 at 10 50 08 am](https://user-images.githubusercontent.com/4602383/48041884-d394b780-e1b1-11e8-89ff-99c072e7de7a.png)
![screen shot 2018-11-06 at 10 50 23 am](https://user-images.githubusercontent.com/4602383/48041887-d7c0d500-e1b1-11e8-8c91-7b78167371d9.png)

@gubuntu what is PT for `what it can do?` 

> improve contrast between text and background

@carina1000 could you suggest me the colors?

> Users will either want GeoNode functionality - hence search or menus - or they will want GeoSAFE - hence 'Run Analysis' and GeoSAFE menu. So I think the 'Run Analysis' next to 'What is is all about' should be moved next to the search bar

@gubuntu we have `Run Analysis` button at the right top. are you sure want to add next to search bar?

**Comment by carina1000** [comment]
@gubuntu I had a chat with @boney-bun regarding feedbacks this morning

**Comment by gubuntu** [comment]
@raisserafael I've just logged in and all the translations are there, maybe @lucernae was updating the strings

**Comment by gubuntu** [comment]
@boney-bun the header bar shouldn't be transparent
![Screenshot 2018-11-06 at 20.11.26.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ba46167953d2fd0f723be0/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc6417763e7952e32a64c5b178f1132a4f5d595cb053181d1ba6acda6fb4bc2e75820d09b9d93b0b20c76814f9b8d74dbf01bc748c1b81b3ae965e82b96371b8d6d6056b5c17129bfe5a3fa19c4fc95df44ce84b5ca6123071ab.png)

**Comment by raisserafael** [comment]
@gubuntu I have revised translation on django, geonode, geonode-javascript and ingc resources grupe. That seems that changes is not yet reflected to web page. Is their publishing managed by other person from our team? Can you advise me to the next steps on translation.

Iam going to work now on outstanding activities agreed by Admire.

**Comment by gubuntu** [comment]
Thanks @raisserafael, now @lucernae can fetch the translated strings and deploy them to the site

**Comment by gubuntu** [comment]
actually @raisserafael there's still lots for you to do:

<img width="768" alt="screenshot 2018-11-06 at 21 01 08" src="https://user-images.githubusercontent.com/496911/48087140-349aaa80-e207-11e8-916d-1640be046a17.png">

**Comment by boney-bun** [comment]
any thoughts?
i'm going to deploy the changes into testing within an hour and a half.

![landingpage](https://user-images.githubusercontent.com/4602383/48110746-61d76f00-e280-11e8-976d-a7c56bdd13a9.gif)

**Comment by carina1000** [comment]
@boney-bun  please align the "what can it do" more to the right aligned to the screen image

**Comment by boney-bun** [comment]
@carina1000 which one do you prefer:

- right alignment:
![screen shot 2018-11-07 at 12 40 06 pm](https://user-images.githubusercontent.com/4602383/48112735-630d9980-e28a-11e8-849b-be9e530816ca.png)
- center alignment:
![screen shot 2018-11-07 at 12 40 42 pm](https://user-images.githubusercontent.com/4602383/48112740-656ff380-e28a-11e8-9d7e-affdf5a20089.png)

**Comment by boney-bun** [comment]
thanks @carina1000, just realized typo in `What It Can Do`.

latest update:

- EN version:
![screen shot 2018-11-07 at 12 56 37 pm](https://user-images.githubusercontent.com/4602383/48113266-c5679980-e28c-11e8-8906-92dca573d672.png)
![screen shot 2018-11-07 at 12 56 51 pm](https://user-images.githubusercontent.com/4602383/48113277-cc8ea780-e28c-11e8-9392-60eed78c9195.png)
![screen shot 2018-11-07 at 12 57 18 pm](https://user-images.githubusercontent.com/4602383/48113284-d6b0a600-e28c-11e8-9ed2-c73ff2cc555c.png)
![screen shot 2018-11-07 at 12 57 30 pm](https://user-images.githubusercontent.com/4602383/48113288-db755a00-e28c-11e8-9639-49bf8c593614.png)

- PT version:
![screen shot 2018-11-07 at 12 59 22 pm](https://user-images.githubusercontent.com/4602383/48113326-0c558f00-e28d-11e8-8eac-d3c7d7525849.png)
![screen shot 2018-11-07 at 12 59 35 pm](https://user-images.githubusercontent.com/4602383/48113329-0f507f80-e28d-11e8-93b3-4a04554a6f46.png)
![screen shot 2018-11-07 at 12 59 47 pm](https://user-images.githubusercontent.com/4602383/48113335-124b7000-e28d-11e8-8310-b231125715dc.png)

**Comment by carina1000** [comment]
@boney-bun center

**Comment by boney-bun** [comment]
thanks @carina1000 
i'm going to merge kartoza/ingc_geonode_theme#14 and bring it to testing.

**Comment by gubuntu** [comment]
looking much better

@boney-bun one last item - the locale switcher dropdown is not placed nor styled nicely and cuts off the words (didn't you notice that?)

**Comment by boney-bun** [comment]
nice catch @gubuntu 

i definitely missed that part.
tbh, it was the last thing i would look at.
i have fixed the language layout in kartoza/ingc_geonode_theme#18.

the position of the language selector should be moved on the same column as Developer.
 otherwise, it will take the WB logo up.

the EN version:
![screen shot 2018-11-07 at 9 38 28 pm](https://user-images.githubusercontent.com/4602383/48138109-25cef900-e2d6-11e8-8c83-1701c906f1f6.png)

the PT version:
![screen shot 2018-11-07 at 9 42 56 pm](https://user-images.githubusercontent.com/4602383/48138123-2d8e9d80-e2d6-11e8-8672-31b9349c71dd.png)

what do you think @gubuntu ?

**Comment by gubuntu** [comment]
perfect. may as well do https://github.com/kartoza/geonode/issues/519 with this then it will be done
