### ISSUE TITLE
empty string search shows more records than explore!

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geonode#424]
geonode.kartoza.com shows 137 layers in explore mode yet when I do an empty string search it shows 143 layers. How can this be?

**Comment by NyakudyaA** [comment]
@gubuntu When you are in explore layers mode only the spatial layers are searched. When you use an empty string then the search results include documents, maps and every resource available in Geonode.
 
**I do not think this should be considered a bug unless we need to restrict the search on each menu item. The search button is generic to all resources available in Geonode**

 I think this should be added as an enhancement to say when someone is looking at the maps section then a search should restrict him to maps only and where would we put the generic search for all resources

**Comment by gubuntu** [comment]
Thanks @Nyakudya, if that's normal GeoNode behaviour I'll close this, you can put the above as a feature request if you like on geonode/geonode
