### ISSUE TITLE
Check that Layer Upload and Preview applicable on GeoNode 2.8

### ISSUE THREAD

**Issue by lucernae** [kartoza/geonode#433]
Test against kartoza/geonode:2.8.x-qgis_server and fix if it is not working.

depends on #435

**Comment by boney-bun** [comment]
all seems to be working fine. 
consider to close this issue.

![geonode 433](https://user-images.githubusercontent.com/4602383/41291355-ae1ec3e8-6e79-11e8-8d20-f82641d0a1b8.gif)

**Comment by lucernae** [comment]
@myarjunar and I got errors on when trying to upload vector layers.
I will deploy testing instance shortly

**Comment by gubuntu** [comment]
@boney-bun why did you size this as 8 if it's done? I'm closing but open if I've misunderstood
