### ISSUE TITLE
Layer Upload not working for Vector Layers

### ISSUE THREAD

**Issue by lucernae** [kartoza/geonode#435]
When we upload vector layer, the EPSG code didn't get read. So, srid of the layer were saved as 'EPSG:None'.

The problem might be very deep in EPSG detection on GeoNode. We might have to file bugfix and unittest on upstream.

child of #457

**Comment by NyakudyaA** [comment]
This has been fixed. The layers with EPSG 4326 are visible as well as other projections. Custom projections will not be loaded and a user is given notice to upload the data n commonly used gdal EPSG codes
