### ISSUE TITLE
geonode doesn't support geojson?

### ISSUE THREAD

**Issue by boney-bun** [kartoza/geonode#444]
tried to upload small_grid layer from this repo: (https://github.com/inasafe/inasafe-headless/tree/develop/src/headless/tasks/test/data/input_layers), then got this message:
![screen shot 2018-07-05 at 3 23 48 pm](https://user-images.githubusercontent.com/4602383/42311253-97f3e152-8067-11e8-81b2-04dd9d5e56a6.png)

does geonode support geojson?

**Comment by NyakudyaA** [comment]
hi, @boney-bun I think the default geonode does not support a lot of formats including geojson. I think for incorporating this formats there are already solutions implemented like https://github.com/GeoNode/django-osgeo-importer. I am not sure you can close this ticket

**Comment by lucernae** [comment]
@boney-bun yes they haven't but QGIS Server should be able to read it natively.
You just need to add Geojson extension in supported list for QGIS Server backend.

**Comment by myarjunar** [comment]
duplicate #405
