### ISSUE TITLE
layer download qgis project file needs extension

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geonode#453]
add .qgs

**Comment by boney-bun** [comment]
i'm wondering why you created this ticket.
than i realized this is a problem using firefox.
chrome and safari don't have this problem.
the extension will be added when we download a layer.

**Comment by gubuntu** [comment]
???

I made this ticket because the downloaded file DOES NOT have the qgs extension. Firefox 61. 

Fix, but not in this sprint

**Comment by NyakudyaA** [comment]
Is this still an issue ?. I can download the file with the extension from Firefox 62.

**Comment by gubuntu** [comment]
yes it has extension now
