### ISSUE TITLE
Download metadata is not working with QGIS backend

### ISSUE THREAD

**Issue by timlinux** [kartoza/geonode#48]
# Problem

If I go here:

http://geonode.kartoza.com/layers/geonode%3Abuildings

Then click download metadata:

![screen shot 2016-05-13 at 10 54 11](https://cloud.githubusercontent.com/assets/178003/15242938/18a9da64-18f9-11e6-925d-e67cb021eb71.png)

Clicking on any link gives an error:

http://localhost:8000/catalogue/csw?outputschema=http%3A%2F%2Fwww.w3.org%2F2005%2FAtom&service=CSW&request=GetRecordById&version=2.0.2&elementsetname=full&id=92081966-07f1-11e6-aa40-6c626d6da409
# Proposed Solution:
- Disable links that go to geoserver
- Provide single link to download ISO19115 XML

**Comment by Gustry** [comment]
And the button "Download layer" gives a link to a TMS (with {Z}, {X} and {Y} included), it's not very user-friendly. I expect to download the layer as a zip when I click on that button.
![3858](https://cloud.githubusercontent.com/assets/1609292/15281909/9f84860c-1b69-11e6-8041-4d0ea970319e.png)

**Comment by ismailsunni** [comment]
Hi
What should be the url of the tiles? In geonode.inasafe.org, it links to `
```
http://geonode.inasafe.org/geoserver/gwc/service/gmaps?layers=geonode:buildings_osm_maumere&zoom={z}&x={x}&y={y}&format=image/png8
```
which also gives error, `400: For input string: "{z}"`

Btw, in this layer, `http://geonode.kartoza.com/layers/geonode%3Atmp0_woay` there is the zipper shape file link (and in some other layers also). But, in this layer `http://geonode.kartoza.com/layers/geonode%3Atmpm75wyf` there is not the zipped shapefile links

**Comment by gubuntu** [comment]
works for me
