### ISSUE TITLE
Uploading raster issues

### ISSUE THREAD

**Issue by timlinux** [kartoza/geonode#49]
# Problem

* After uploading a raster it is not visible in the layer preview
* It has no thumbnail

See for example http://geonode.kartoza.com/layers/geonode%3Aflood_laplata_2002_epsg4326

**Comment by Gustry** [comment]
I can see the thumbnail here : http://198.50.229.90/layers/?limit=100&offset=0
And I can see the layer : http://198.50.229.90/layers/geonode%3Apopulation_count

Maybe the issue is when you import your layer only

**Comment by Gustry** [comment]
https://github.com/Gustry/geonode/commit/a04e754570753c1c48e56a627c440bbfc5469968
