### ISSUE TITLE
WMS download links have wrong extent

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geonode#492]
I downloaded the qgs file of http://testing.geonode.kartoza.com/layers/geonode:roads_33s and the WMS layer worked, but zoom to layer zoomed to the whole world, so somewhere the layer extent is being miserepresented. 

Check that extents are being described properly

**Comment by NyakudyaA** [comment]
I have tested with http://testing.geonode.kartoza.com/layers/geonode:pop_post_ine and http://testing.geonode.kartoza.com/layers/geonode:national_flood_high_new_1. The layers render fine in QGIS

These layers are in UTM and EPSG:4326 respectively
