### ISSUE TITLE
publish MZ Facebook population data

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geonode#493]
Please download the Facebook population data for Mozambique directly onto the INGC server along with the XML from @raisserafael containing InaSAFE 4 keywords and publish in GeoNode

**Comment by NyakudyaA** [comment]
Added the Facebook population into the Geonode - Awaiting Jose to supply the metadata XML with keywords.
![facebook](https://user-images.githubusercontent.com/2510900/46344903-f7109380-c642-11e8-9890-1eee7cb69f60.png)

**Comment by gubuntu** [comment]
@raisserafael please supply InaSAFE keywords. 

@NyakudyaA the legend says 'pixels per person' - doesn't make sense. Surely should be 'persons per pixel' and the colours in the legend don't match the values (are you sure you're using the correct band?) Dense population in Maputo is red which is the lowest population density in your legend

**Comment by NyakudyaA** [comment]
I will look at it and correct the colours and the label

**Comment by NyakudyaA** [comment]
This has been updated and now can be seen in GeoSAFE
![screenshot 2018-10-17 at 20 17 10](https://user-images.githubusercontent.com/2510900/47107482-ba9b8500-d249-11e8-9f6f-26657df51521.png)
