### ISSUE TITLE
Thumbnails should be of  standard size across backends

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geonode#497]
# Problem
When using QGIS Server vs Geoserver backend the thumbnails generated are of different dimensions.

We need to decide which approach is better.

Example of the same layer uploaded in the different backends
QGIS -Server Backend
![qgsi-server](https://user-images.githubusercontent.com/2510900/46337488-ec97cf00-c62d-11e8-8168-426fba968e18.png)

Geoserver Backend
![layer-4370ae3a-c61c-11e8-9590-027bd5c50f8c-thumb](https://user-images.githubusercontent.com/2510900/46337645-52845680-c62e-11e8-90fe-6802311674a8.png)

# Solutions
* Is the QGIS Server approach good - If so then let's make a PR upstream with this
* Is the Geoserver approach better. If so Can we adopt it?
* Can we achieve a compromise on which method is better or we just ignore it

**Comment by gubuntu** [comment]
For QGIS I originally wanted layer aspect ratio to be maintained while being forced to fit into a standard sized div, and to always have a basemap. I don't like how Geoserver thumbnails are squashed. 

However, the guys implemented nice thumbnails maintaining aspect ratio, but not in a fixed div. So as an enhancement definitely use our QGIS approach, but in a fixed div. 

To do this all that needs to be done is to add the div dimensions to the thumbnail WMS request. i.e. full extent of layer with div dimensions for image size.

**Comment by lucernae** [comment]
We do this by allowing the user to set the thumbnail extent themselves when they want it to be square like the map (But it doesn't seem to work now). The default thumbnail is still like that.

If we want a fixed div, i don't know how to make the extent square. do we have global projection where the unit is in meters?

**Comment by gubuntu** [comment]
1. you don't need to worry about projections as I've explained before. You just make a request with the bounding box you want and the image size in pixels you want returned and WMS does the rest. You should get a perfectly sized image for the target div with the gis layer in the right proportions. 

1. where can the user set the thumbnail extent?

**Comment by gubuntu** [comment]
this isn't difficult and we have some thumbnails that were done correctly. In any case the current implementation is all over the place.

it shouldn't need GEOS or projection libraries

1. use the 3857 bbox of the layer (which is global in meters)
1. which is greater, h or w?
  a. if bbox h  is greater, match that to the fixed height of the div as your image height parameter
  a. if bbox w is greater, match that to the fixed width of the div as your image width parameter
1. use the aspect ratio of the bbox to  solve for the missing image  dimension. 
1. centre the image horizontally and vertically in the div without stretching it to fit

**Comment by boney-bun** [comment]
even the geoserver's thumbnail seems to be squashed for the non-square extent as in the OP.

let me try  @gubuntu's suggestion on my machine first.

**Comment by lucernae** [comment]
Ok, the key is here @boney-bun 

> 1. use the 3857 bbox of the layer (which is global in meters)

Just operate using 3857 when doing the scaling calculation. If this is in meters, then we're done.
The original GeoNode image ratio is 200x150 pixel.

Just scale the new bbox using that ratios

**Comment by gubuntu** [comment]
our GeoNode QGIS server is now using the standard GeoNode div for thumbnails
