### ISSUE TITLE
Vector attributes do not show

### ISSUE THREAD

**Issue by timlinux** [kartoza/geonode#50]
When viewing a vector layer there are
![screen shot 2016-05-13 at 11 05 31](https://cloud.githubusercontent.com/assets/178003/15243344/39090af8-18fb-11e6-82ff-a415a3d89087.png)
 no attributes listed. We should get something like this:

(From demo site at http://198.50.229.90/layers/geonode%3Aopendri_admin)

In our site we get more like this:

http://geonode.kartoza.com/layers/geonode%3Abuildings

![screen shot 2016-05-13 at 11 11 00](https://cloud.githubusercontent.com/assets/178003/15243377/6be9b2d8-18fb-11e6-8176-e3815d2c4e87.png)

**Comment by Gustry** [comment]
How it looks like on geonode.inasafe.org : 
http://geonode.inasafe.org/layers/geonode%3Abuilding_points

**Comment by Gustry** [comment]
Fixed in https://github.com/Gustry/geonode/commit/3b526fa41f508d3ad47e078ab280b899eb5164a8 and 79dedd805f10c369e8aa506229c5a4a726438296

**Comment by timlinux** [comment]
Thanks @Gustry !

**Comment by Gustry** [comment]
The attribute is gone again : http://geonode.kartoza.com/layers/geonode%3Abuildings
