### ISSUE TITLE
still lots of English strings in PT version

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geonode#508]
have a look at the layers page, for example. Some strings are translated but many are not. 

would those be in the INGC theme or coming from the main geonode project?

**Comment by myarjunar** [comment]
I think the translation on every page other than geosafe's and landing page is coming from geonode itself. We need to somehow update the PT translation in our geonode repo. CMIIW @lucernae

**Comment by gubuntu** [comment]
OK, GeoNode translation is in https://github.com/kartoza/geonode/issues/429 

We need to push upstream soon (for 2.8.1 and 2.10) so we don't diverge too much. I don't want to do a separate translation in my fork.
