### ISSUE TITLE
Map link not working (404)

### ISSUE THREAD

**Issue by timlinux** [kartoza/geonode#51]
Oh the map list page:

http://geonode.kartoza.com/maps/?limit=100&offset=0

![screen shot 2016-05-13 at 11 13 47](https://cloud.githubusercontent.com/assets/178003/15243424/ca6750ae-18fb-11e6-8bbd-2cb904d4cf18.png)

Clicking on this link gives 404

http://geonode.kartoza.com/maps/55

**Comment by timlinux** [comment]
Also please check the other links work:

* http://geonode.kartoza.com/maps/55#info
* http://geonode.kartoza.com/maps/55#share
* http://geonode.kartoza.com/maps/55/view

**Comment by gubuntu** [comment]
all working except info, creating new ticket
