### ISSUE TITLE
Create Tile seeder management command

### ISSUE THREAD

**Issue by lucernae** [kartoza/geonode#513]
Related with #422

New bounds and can be recalculated by triggering save signals. But the tile cache can not.

**Comment by lucernae** [comment]
The plan to use this management command in Rancher is to clone service from django and create a run once service for each layer. Then with `--noinput` option, provide the command like this:

![Screen Shot 2018-11-02 at 15.28.27.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54d0705f7637910300055208/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226454f16b7191a379ea0c2959415d49be5d4a1f06a3a3dc78e2a436628f545aef85650920923c44a9ed824aed01ba26df48d1b2b99850d2aa6c7bb3d4d216744b470a83ed5c3caa984ecc59f74fe64e56a01b3764f43b.png)

(Important settings, will be `run once`, `command` and `entry point`. We uses celery entry point because it will not deal with migrate and collectstatic instance.)

Last, define the schedule here:

![Screen Shot 2018-11-02 at 15.36.01.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54d0705f7637910300055208/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226454f16b7191a379ea0c2857415f4fbe5d4a1f06a3a3dc78e2a436628f545aef85650920923c44a9ed824aed01ba26df48d1b2b99850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecc59f74fe64a52a7153064f43b.png)

Unlike regular cron job, Rancher cron schedule starts from seconds. So `0 0 3 * * ?` means every day at 3 A.M.

**Comment by lucernae** [comment]
If executed from command line, it will look like something like this.

![Screen Shot 2018-11-01 at 02.23.38.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54d0705f7637910300055208/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226454f26b7191a378ed0c2952415c46be5d4a1f06a3a3dc78e2a436628f545aef85650920923c44a9ed824aed01ba26df48d1b2b99850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecc59f74fe84d56a7103762f43b.png)

I'm currently trying it on testing using above plan, but the command doesn't execute. I'm trying to figure out why. The command execute normally through django console at testing.

**Comment by lucernae** [comment]
Ok, I think I understand. The log output in rancher only shows up after the command finished, so we can't see the progress. But the command ran

**Comment by NyakudyaA** [comment]
The seeding is working fine
![screenshot 2018-11-13 at 21 00 40](https://user-images.githubusercontent.com/2510900/48437312-ab94ed80-e789-11e8-989d-1279076d156b.png)
