### ISSUE TITLE
update WB logo

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geonode#519]
Please apply once received from @cgiovando

**Comment by cgiovando** [comment]
You can use this http://www.worldbank.org/content/dam/wbr/logo/logo-wb-header-en.svg

**Comment by boney-bun** [comment]
- EN version:
![screen shot 2018-11-12 at 1 35 47 pm](https://user-images.githubusercontent.com/4602383/48330952-1f979e80-e681-11e8-9b7c-ed88154618a3.png)

- PT version:
![screen shot 2018-11-12 at 1 35 29 pm](https://user-images.githubusercontent.com/4602383/48330953-21f9f880-e681-11e8-9df0-e12a434f0d30.png)

**Comment by gubuntu** [comment]
LGTM

**Comment by NyakudyaA** [comment]
World bank logo appears in both version English and PT
