### ISSUE TITLE
Cyclone, drought landslide layers

### ISSUE THREAD

**Issue by raisserafael** [kartoza/geonode#523]
@gubuntu @NyakudyaA 

Cyclone and drought layers will not be useful for impact analysis since that has not yet supported by Geosafe. Can we agree to leave it just available as context layer on data layer list?

—

**Comment by NyakudyaA** [comment]
@raisserafael If the layer is available in Geonode as a context layer then it is fine.

**Comment by gubuntu** [comment]
superseded by #518
