### ISSUE TITLE
More paper cuts for InaSAFE Create Analysis

### ISSUE THREAD

**Issue by timlinux** [kartoza/geonode#53]
## Fix pop out titles:
- [x] Select a population layer
- [x] Select the structure -> Select a structure layer
- [x] Select a roads layer
- [x] Select a flood layer
- [ ] Select a tsunami layer   **needs to be added**
- [x] Select an impact layer
## IF button

If layers are not appropriate to provide an valid IF, show this text in the pop out:

> No impact functions are available. In order to run the analysis you need to select one hazard layer (flood, tsunami, volcano, earthquake etc.) and one exposure layer (population, structure, roads).

**Comment by lucernae** [comment]
- [ ] pop up when there is empty impact layer should encourage user to create analysis instead of uploading a layer

**Comment by timlinux** [comment]
We should add landcover exposure too.

**Comment by gubuntu** [comment]
This issue was moved to kartoza/geosafe#118
