### ISSUE TITLE
changed on transifex not yet reflected on web page

### ISSUE THREAD

**Issue by raisserafael** [kartoza/geonode#537]
@gubuntu @NyakudyaA  See below deleted words (highlighted circle in yellow) but still in the page ( highlighted circle in red). That was saved and reviewed week ego.
![capture](https://user-images.githubusercontent.com/33931553/49090553-a98d5d00-f266-11e8-8739-a0fa94cd3098.JPG)
![capture_front_page](https://user-images.githubusercontent.com/33931553/49090555-aa25f380-f266-11e8-9b6c-96a502c72999.JPG)

**Comment by gubuntu** [comment]
@boney-bun please pull all the latest translations and deploy and check this is fixed.

**Comment by boney-bun** [comment]
done.
![Screen Shot 2019-01-11 at 11.37.09 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58cac11cd032f92000868ac7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77226455f26b7191a379ee0c2856415f47bc30254d58eeb9cb74fce36f34985619e8d93c5d20ce6b45f8b9d71aea01ef728b4f83e2bbde48c5fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34fe64c5da517326be574376e0a.png)

probably you need to review and approve the PT translation for those 2 words in transifex.

i've updated the repo too. the PR is in kartoza/ingc_geonode_theme#32
