### ISSUE TITLE
Duplicate files when we upload a layer

### ISSUE THREAD

**Issue by Gustry** [kartoza/geonode#61]
When we upload a layer, it copies the layer correctly, but it also duplicates the layer with the extension `.tif` included.

![3858](https://cloud.githubusercontent.com/assets/1609292/15280993/2e947c66-1b61-11e6-847d-2bf1a3fcd8da.png)

**Comment by gubuntu** [comment]
is this still an issue @Gustry? I shouldn't think so. Please close if it's not

**Comment by gubuntu** [comment]
ping @Gustry

**Comment by NyakudyaA** [comment]
I have tested this and the layer does not duplicate.
![no_dups](https://user-images.githubusercontent.com/2510900/45107399-c4ee3d80-b139-11e8-9d96-adf36fc1b0fa.png)
