### ISSUE TITLE
Put hazard layer below exposure layer?

### ISSUE THREAD

**Issue by vdeparday** [kartoza/geonode#78]
I am not sure if it would work in all cases but I think when looking at buildings and hazard we should likely put hazard layer below and maybe play with transparency.

The tricky is when we have a raster for exposure too.

![image](https://cloud.githubusercontent.com/assets/1036189/15672701/dc8ad3b6-274f-11e6-9972-108b050096f4.png)

**Comment by timlinux** [comment]
Hi @vdeparday I agree, in the general case having hazard below exposure is going to be a better fit I think. Later I think we could maybe try to use some contextual rules (e.g. if exposure is raster and hazard is vector, put exposure below), but for now having exposure on top will probably be good.

@lucernae will you see to that?

**Comment by gubuntu** [comment]
This issue was moved to kartoza/geosafe#262
