### ISSUE TITLE
Create an 'embed this' link

### ISSUE THREAD

**Issue by timlinux** [kartoza/geonode#86]
Another thing (kind of link) we could do is an 'embed this' link which takes you to a view showing

We can give a tile url back like this for now:

```
http://foo.com/qgis-server/tiles/buildings_1/{z}/{x}/{y}.png
```

Or even a tile layer snippet for leaflet like this:

```
        tile_layer = L.tileLayer("/qgis-server/tiles/buildings_1/{z}/{x}/{y}.png",
        {
         'opacity':0.8
        });
```

Or even a whole 'embed' snippet which includes a fully working leaflet widget.

**Comment by gubuntu** [comment]
all done
